import 'package:flutter/material.dart';
import 'package:myitihas/pages/map2/plan/booking_operator.dart';

/// Central configuration for travel booking operators and their deep links
class TravelBookingConfig {
  static const Map<TravelMode, List<BookingOperator>> operatorsByMode = {
    TravelMode.train: [
      BookingOperator(
        id: 'irctc',
        name: 'IRCTC',
        travelMode: TravelMode.train,
        deepLinkTemplate: 'https://www.irctc.co.in/nget/train-search',
        color: Color(0xFF00A699),
        icon: Icons.train,
        isVerified: true,
        description: 'Indian Railways - Official ticket booking',
      ),
      BookingOperator(
        id: 'railyatri',
        name: 'RailYatri',
        travelMode: TravelMode.train,
        deepLinkTemplate: 'https://www.railyatri.in/train-search',
        color: Color(0xFF1E88E5),
        icon: Icons.train,
        isVerified: true,
        description: 'Smart train ticket booking',
      ),
      BookingOperator(
        id: 'ixigo_train',
        name: 'ixigo',
        travelMode: TravelMode.train,
        deepLinkTemplate: 'https://www.ixigo.com/trains',
        color: Color(0xFFFF6B6B),
        icon: Icons.train,
        isVerified: true,
        description: 'Book trains with ixigo',
      ),
      BookingOperator(
        id: 'goibibo_train',
        name: 'Goibibo',
        travelMode: TravelMode.train,
        deepLinkTemplate: 'https://www.goibibo.com/train/',
        color: Color(0xFF7C3AED),
        icon: Icons.train,
        isVerified: true,
        description: 'Goibibo train bookings',
      ),
      BookingOperator(
        id: 'yatra_train',
        name: 'Yatra',
        travelMode: TravelMode.train,
        deepLinkTemplate: 'https://www.yatra.com/trains',
        color: Color(0xFFFD7E14),
        icon: Icons.train,
        isVerified: true,
        description: 'Yatra train search',
      ),
    ],
    TravelMode.flight: [
      BookingOperator(
        id: 'mmt_flight',
        name: 'MakeMyTrip',
        travelMode: TravelMode.flight,
        deepLinkTemplate: 'https://www.makemytrip.com/flights',
        color: Color(0xFF003580),
        icon: Icons.flight,
        isVerified: true,
        description: 'MakeMyTrip - Flight bookings',
      ),
      BookingOperator(
        id: 'ixigo_flight',
        name: 'ixigo',
        travelMode: TravelMode.flight,
        deepLinkTemplate: 'https://www.ixigo.com/flights',
        color: Color(0xFFFF6B6B),
        icon: Icons.flight,
        isVerified: true,
        description: 'Book flights with ixigo',
      ),
      BookingOperator(
        id: 'skyscanner',
        name: 'Skyscanner',
        travelMode: TravelMode.flight,
        deepLinkTemplate: 'https://www.skyscanner.com/flights',
        color: Color(0xFF003580),
        icon: Icons.flight,
        isVerified: true,
        description: 'Compare flight prices',
      ),
      BookingOperator(
        id: 'goibibo_flight',
        name: 'Goibibo',
        travelMode: TravelMode.flight,
        deepLinkTemplate: 'https://www.goibibo.com/flights/',
        color: Color(0xFF7C3AED),
        icon: Icons.flight,
        isVerified: true,
        description: 'Goibibo flights',
      ),
      BookingOperator(
        id: 'expedia',
        name: 'Expedia',
        travelMode: TravelMode.flight,
        deepLinkTemplate: 'https://www.expedia.com/flights',
        color: Color(0xFFFFD700),
        icon: Icons.flight,
        isVerified: true,
        description: 'Expedia flights',
      ),
      BookingOperator(
        id: 'flydubai',
        name: 'FlyDubai',
        travelMode: TravelMode.flight,
        deepLinkTemplate: 'https://www.flydubai.com/en/flights',
        color: Color(0xFFCC1C1C),
        icon: Icons.flight,
        isVerified: false,
        description: 'FlyDubai flights',
      ),
      BookingOperator(
        id: 'yatra_flight',
        name: 'Yatra',
        travelMode: TravelMode.flight,
        deepLinkTemplate: 'https://www.yatra.com/flights',
        color: Color(0xFFFD7E14),
        icon: Icons.flight,
        isVerified: true,
        description: 'Yatra flights',
      ),
    ],
    TravelMode.bus: [
      BookingOperator(
        id: 'redbus',
        name: 'RedBus',
        travelMode: TravelMode.bus,
        deepLinkTemplate: 'https://www.redbus.in/bus-tickets',
        color: Color(0xFFE91E63),
        icon: Icons.directions_bus,
        isVerified: true,
        description: 'RedBus - India\'s largest bus booking platform',
      ),
      BookingOperator(
        id: 'abhibus',
        name: 'AbhiBus',
        travelMode: TravelMode.bus,
        deepLinkTemplate: 'https://www.abhibus.com',
        color: Color(0xFFFF5722),
        icon: Icons.directions_bus,
        isVerified: true,
        description: 'AbhiBus bus bookings',
      ),
      BookingOperator(
        id: 'ixigo_bus',
        name: 'ixigo',
        travelMode: TravelMode.bus,
        deepLinkTemplate: 'https://www.ixigo.com/buses',
        color: Color(0xFFFF6B6B),
        icon: Icons.directions_bus,
        isVerified: true,
        description: 'Book buses with ixigo',
      ),
      BookingOperator(
        id: 'goibibo_bus',
        name: 'Goibibo',
        travelMode: TravelMode.bus,
        deepLinkTemplate: 'https://www.goibibo.com/buses/',
        color: Color(0xFF7C3AED),
        icon: Icons.directions_bus,
        isVerified: true,
        description: 'Goibibo bus bookings',
      ),
      BookingOperator(
        id: 'yatra_bus',
        name: 'Yatra',
        travelMode: TravelMode.bus,
        deepLinkTemplate: 'https://www.yatra.com/buses',
        color: Color(0xFFFD7E14),
        icon: Icons.directions_bus,
        isVerified: true,
        description: 'Yatra buses',
      ),
      BookingOperator(
        id: 'bushire',
        name: 'BusHire',
        travelMode: TravelMode.bus,
        deepLinkTemplate: 'https://www.bushire.com',
        color: Color(0xFF1E88E5),
        icon: Icons.directions_bus,
        isVerified: false,
        description: 'Bus charter and bookings',
      ),
    ],
    TravelMode.hotel: [
      BookingOperator(
        id: 'oyo',
        name: 'OYO',
        travelMode: TravelMode.hotel,
        deepLinkTemplate: 'https://www.oyo.com/hotels',
        color: Color(0xFFEA7D22),
        icon: Icons.hotel,
        isVerified: true,
        description: 'OYO - Budget hotels and stays',
      ),
      BookingOperator(
        id: 'booking_com',
        name: 'Booking.com',
        travelMode: TravelMode.hotel,
        deepLinkTemplate: 'https://www.booking.com',
        color: Color(0xFF003580),
        icon: Icons.hotel,
        isVerified: true,
        description: 'Booking.com - Hotels worldwide',
      ),
      BookingOperator(
        id: 'mmt_hotel',
        name: 'MakeMyTrip',
        travelMode: TravelMode.hotel,
        deepLinkTemplate: 'https://www.makemytrip.com/hotels',
        color: Color(0xFF003580),
        icon: Icons.hotel,
        isVerified: true,
        description: 'MakeMyTrip hotels',
      ),
      BookingOperator(
        id: 'ixigo_hotel',
        name: 'ixigo',
        travelMode: TravelMode.hotel,
        deepLinkTemplate: 'https://www.ixigo.com/hotels',
        color: Color(0xFFFF6B6B),
        icon: Icons.hotel,
        isVerified: true,
        description: 'ixigo hotels',
      ),
      BookingOperator(
        id: 'trivago',
        name: 'Trivago',
        travelMode: TravelMode.hotel,
        deepLinkTemplate: 'https://www.trivago.com',
        color: Color(0xFF4CAF50),
        icon: Icons.hotel,
        isVerified: true,
        description: 'Trivago - Compare hotel prices',
      ),
      BookingOperator(
        id: 'agoda',
        name: 'Agoda',
        travelMode: TravelMode.hotel,
        deepLinkTemplate: 'https://www.agoda.com',
        color: Color(0xFF0066CC),
        icon: Icons.hotel,
        isVerified: true,
        description: 'Agoda hotels',
      ),
    ],
    TravelMode.car: [
      BookingOperator(
        id: 'zoomcar',
        name: 'Zoomcar',
        travelMode: TravelMode.car,
        deepLinkTemplate: 'https://www.zoomcar.com/cars',
        color: Color(0xFF42A5F5),
        icon: Icons.directions_car,
        isVerified: true,
        description: 'Zoomcar - Self-drive rentals',
      ),
      BookingOperator(
        id: 'avis',
        name: 'Avis',
        travelMode: TravelMode.car,
        deepLinkTemplate: 'https://www.avis.co.in',
        color: Color(0xFFE74C3C),
        icon: Icons.directions_car,
        isVerified: true,
        description: 'Avis car rentals',
      ),
      BookingOperator(
        id: 'revv',
        name: 'Revv',
        travelMode: TravelMode.car,
        deepLinkTemplate: 'https://www.revv.co.in',
        color: Color(0xFF00BCD4),
        icon: Icons.directions_car,
        isVerified: true,
        description: 'Revv - Car subscriptions',
      ),
      BookingOperator(
        id: 'savaari',
        name: 'Savaari',
        travelMode: TravelMode.car,
        deepLinkTemplate: 'https://www.savaari.com',
        color: Color(0xFF9C27B0),
        icon: Icons.directions_car,
        isVerified: false,
        description: 'Savaari - Intercity cabs',
      ),
      BookingOperator(
        id: 'ixigo_car',
        name: 'ixigo',
        travelMode: TravelMode.car,
        deepLinkTemplate: 'https://www.ixigo.com/cars',
        color: Color(0xFFFF6B6B),
        icon: Icons.directions_car,
        isVerified: true,
        description: 'ixigo car rentals',
      ),
    ],
  };

  /// Get operators for a specific travel mode
  static List<BookingOperator> getOperatorsForMode(TravelMode mode) {
    return operatorsByMode[mode] ?? [];
  }

  /// Get operator by ID (cross-mode lookup)
  static BookingOperator? getOperatorById(String id) {
    for (final operators in operatorsByMode.values) {
      try {
        return operators.firstWhere((op) => op.id == id);
      } catch (_) {
        continue;
      }
    }
    return null;
  }

  /// Get all travel modes that have operators
  static List<TravelMode> getAllTravelModes() {
    return operatorsByMode.keys.toList();
  }
}
