import 'dart:convert';

import 'package:fpdart/fpdart.dart';
import 'package:injectable/injectable.dart';
import 'package:myitihas/core/errors/failures.dart';
import 'package:myitihas/features/social/data/datasources/user_remote_data_source.dart';
import 'package:myitihas/features/stories/domain/entities/story.dart';
import 'package:myitihas/features/story_generator/domain/entities/story_chat_message.dart';
import 'package:myitihas/features/story_generator/domain/entities/story_prompt.dart';
import 'package:myitihas/features/story_generator/domain/entities/generator_options.dart';
import 'package:myitihas/features/story_generator/domain/entities/story_translation.dart';
import 'package:myitihas/features/story_generator/domain/repositories/story_generator_repository.dart';
import 'package:myitihas/services/supabase_service.dart';
import 'package:myitihas/repository/my_itihas_repository.dart';
import 'package:myitihas/features/stories/data/models/story.model.dart';
import 'package:myitihas/features/story_generator/data/models/story_chat_conversation.model.dart';
import 'package:brick_offline_first/brick_offline_first.dart';
import 'package:myitihas/core/utils/app_error_message.dart';
import 'package:myitihas/core/utils/language_voice_resolver.dart';
import '../datasources/remote_story_generator_datasource.dart';
import '../datasources/mock_story_generator_datasource.dart';

@LazySingleton(as: StoryGeneratorRepository)
class StoryGeneratorRepositoryImpl implements StoryGeneratorRepository {
  static const String _insightsOwnerOnlyMessage =
      'Story insights and interactions are available only for stories generated by the current user.';
  final RemoteStoryGeneratorDataSource _remoteDataSource;
  final MockStoryGeneratorDataSource _mockDataSource;
  final MyItihasRepository repository;

  StoryGeneratorRepositoryImpl(
    this._remoteDataSource,
    this._mockDataSource,
    this.repository,
  );

  @override
  Future<Either<Failure, Story>> generateStory({
    required StoryPrompt prompt,
    required GeneratorOptions options,
  }) async {
    try {
      final result = await _remoteDataSource.generateStory(
        prompt: prompt,
        options: options,
      );

      final user = SupabaseService.client.auth.currentUser;
      final userRepo = UserRemoteDataSourceSupabase(SupabaseService.client);
      final author = await userRepo.getUserById(user!.id);
      final title = result['title'] as String? ?? 'Untitled Story';
      final storyContent = result['story'] as String? ?? '';
      final moral = result['moral'] as String? ?? '';
      final reference = result['reference'] as String? ?? '';
      final characters = (result['characters'] as List<dynamic>? ?? const [])
          .map((e) => e.toString())
          .toList();

      // Extract LLM-provided attributes (if any)
      final attributes =
          (result['attributes'] as Map?)?.cast<String, dynamic>() ??
          <String, dynamic>{};

      final scriptureFromAttributes =
          (attributes['references'] is List &&
              (attributes['references'] as List).isNotEmpty)
          ? (attributes['references'] as List).first.toString()
          : null;
      final scriptureFromResult = result['scripture'] as String?;

      // LLM-first scripture selection, then prompt, then generic fallback
      final scripture = (scriptureFromAttributes?.trim().isNotEmpty ?? false)
          ? scriptureFromAttributes!.trim()
          : (scriptureFromResult?.trim().isNotEmpty ?? false)
          ? scriptureFromResult!.trim()
          : (prompt.scripture?.trim().isNotEmpty ?? false)
          ? prompt.scripture!.trim()
          : 'Unknown';

      final triviaFromLlm = (result['trivia'] as String?)?.trim() ?? '';
      final quotesFromLlm = (result['quotes'] as String?)?.trim() ?? '';
      final activityFromLlm = (result['activity'] as String?)?.trim() ?? '';

      // Local fallback generation for UI fields when LLM does not provide them
      final theme = prompt.theme ?? 'Dharma';

      final storyMap = {
        'user_id': user.id,
        'title': title,
        'content': storyContent,
        'language': options.language.displayName,
        'metadata': {
          'scripture': scripture,
          'trivia': triviaFromLlm,
          'quotes': quotesFromLlm,
          'activity': activityFromLlm,
          'lesson': moral,
        },
        'attributes': {
          'quotes': quotesFromLlm.isNotEmpty
              ? quotesFromLlm
              : _getQuotes(theme),
          'trivia': triviaFromLlm.isNotEmpty
              ? triviaFromLlm
              : _getTrivia(scripture),
          'activity': activityFromLlm.isNotEmpty
              ? activityFromLlm
              : _getActivity(theme),
          'scripture': scripture,
          'theme': theme,
          'references':
              attributes['references'] ??
              (reference.isNotEmpty ? reference : scripture),
          'characters': attributes['characters'] ?? characters,
          'character_details': <String, dynamic>{},
          'moral': moral.isNotEmpty ? moral : _getLesson(theme),
          'story_type': prompt.storyType,
          'main_character_type': prompt.mainCharacter,
          'story_setting': prompt.setting,
          'time_era': prompt.scriptureSubtype ?? scripture,
          'narrative_perspective': 'Third Person',
          'language_style': options.language.displayName,
          'emotional_tone': 'Inspiring',
          'narrative_style': options.format.displayName,
          'plot_structure':
              '${options.length.displayName} ${options.length.description}',
          'story_length':
              '${options.length.displayName} ${options.length.description}',
          'tags': <String>[],
          'translations': {
            languageNameToCode(options.language.displayName): TranslatedStory(
              title: title,
              story: storyContent,
              moral: moral,
              trivia: triviaFromLlm.isNotEmpty
                  ? triviaFromLlm
                  : _getTrivia(scripture),
              lang: languageNameToCode(options.language.displayName),
            ),
          },
        },
        'author_id': author.id,
        'comment_count': 0,
        'share_count': 0,
        'likes': 0,
        'views': 0,
        'published_at': null,
        'image_url': null,
        'author': author.displayName,
        'is_favourite': false,
      };

      final response = await SupabaseService.client
          .from('stories')
          .insert(storyMap)
          .select()
          .single();

      final story = _mapSupabaseRowToStory(response);

      // Cache to local SQLite only (Supabase already has the record)
      // Use sqliteProvider directly to avoid any remote sync attempts
      await repository.sqliteProvider.upsert<StoryModel>(
        StoryModel.fromDomain(story),
        repository: repository,
      );

      return Right(story);
    } catch (e) {
      return Left(
        ServerFailure(
          toUserFriendlyErrorMessage(e, fallback: 'Failed to generate story'),
        ),
      );
    }
  }

  @override
  Future<Either<Failure, StoryPrompt>> getRandomOptions() async {
    try {
      final options = await _mockDataSource.getRandomOptions();
      return Right(options);
    } catch (e) {
      return Left(
        ServerFailure('Failed to get random options: ${e.toString()}'),
      );
    }
  }

  @override
  Future<Either<Failure, Story>> getStoryById(String storyId) async {
    try {
      final user = SupabaseService.client.auth.currentUser;
      if (user == null) {
        return Left(ServerFailure('User not authenticated'));
      }

      // Fetch directly from Supabase to ensure we get the latest image_url
      final response = await SupabaseService.client
          .from('stories')
          .select()
          .eq('id', storyId)
          .maybeSingle();

      if (response == null) {
        // Fallback to local cache if not found in Supabase
        final models = await repository.get<StoryModel>(
          policy: OfflineFirstGetPolicy.localOnly,
          query: Query.where('id', storyId),
        );

        if (models.isEmpty) {
          return Left(NotFoundFailure('Story not found'));
        }

        return Right(models.first.toDomain());
      }

      final story = _mapSupabaseRowToStory(response);
      final isBookmarked = await _isStoryBookmarkedByUser(
        storyId: story.id,
        userId: user.id,
      );
      final hydratedStory = story.copyWith(isFavorite: isBookmarked);

      // Update local cache with fresh data
      await repository.sqliteProvider.upsert<StoryModel>(
        StoryModel.fromDomain(hydratedStory),
        repository: repository,
      );

      return Right(hydratedStory);
    } on OfflineFirstException catch (e) {
      return Left(CacheFailure(e.message));
    } catch (e) {
      return Left(ServerFailure('Failed to fetch story: ${e.toString()}'));
    }
  }

  @override
  Future<Either<Failure, List<Story>>> getStories(int limit) async {
    try {
      final user = SupabaseService.client.auth.currentUser;
      if (user == null) {
        return Left(ServerFailure('User not authenticated'));
      }

      final response = await SupabaseService.client
          .from('stories')
          .select()
          .limit(limit);

      return Right(response.map((row) => _mapSupabaseRowToStory(row)).toList());
    } catch (e) {
      return Left(ServerFailure('Failed to fetch story: ${e.toString()}'));
    }
  }

  @override
  Future<Either<Failure, String>> generateStoryImage({
    required String title,
    required String story,
    required String moral,
  }) async {
    try {
      final imageUrl = await _remoteDataSource.generateStoryImage(
        title: title,
        story: story,
        moral: moral,
      );
      return Right(imageUrl);
    } catch (e) {
      return Left(
        ServerFailure(
          toUserFriendlyErrorMessage(
            e,
            fallback: 'Failed to generate story image',
          ),
        ),
      );
    }
  }

  @override
  Future<Either<Failure, Story>> updateStory(Story story) async {
    try {
      final user = SupabaseService.client.auth.currentUser;
      if (user == null) {
        return Left(ServerFailure('User not authenticated'));
      }

      final data = {
        'id': story.id,
        'user_id': user.id,
        'title': story.title,
        'content': story.story,
        'image_url': story.imageUrl,
        'language': story.attributes.languageStyle,
        'attributes': _attributesToMap(story),
        'is_favourite': story.isFavorite,
        'updated_at': DateTime.now().toIso8601String(),
      };

      final response = await SupabaseService.client
          .from('stories')
          .upsert(data, onConflict: 'id')
          .select()
          .single();

      final updatedStory = _mapSupabaseRowToStory(response);

      // Update the local Brick/SQLite cache only (Supabase already updated above)
      // Use sqliteProvider directly to avoid any remote sync attempts
      final model = StoryModel.fromDomain(updatedStory);
      await repository.sqliteProvider.upsert<StoryModel>(
        model,
        repository: repository,
      );

      return Right(updatedStory);
    } catch (e) {
      return Left(ServerFailure('Failed to save story: ${e.toString()}'));
    }
  }

  @override
  Future<Either<Failure, Story>> likeStory(Story story, bool isLiked) async {
    try {
      final user = SupabaseService.client.auth.currentUser;
      if (user == null) {
        return Left(ServerFailure('User not authenticated'));
      }

      if (isLiked) {
        await SupabaseService.client.from('bookmarks').upsert({
          'user_id': user.id,
          'bookmarkable_type': 'story',
          'bookmarkable_id': story.id,
        }, onConflict: 'user_id,bookmarkable_type,bookmarkable_id');
      } else {
        await SupabaseService.client
            .from('bookmarks')
            .delete()
            .eq('user_id', user.id)
            .eq('bookmarkable_type', 'story')
            .eq('bookmarkable_id', story.id);
      }

      final updatedStory = story.copyWith(isFavorite: isLiked);
      await repository.sqliteProvider.upsert<StoryModel>(
        StoryModel.fromDomain(updatedStory),
        repository: repository,
      );

      return Right(updatedStory);
    } catch (e) {
      return Left(ServerFailure('Failed to save story: ${e.toString()}'));
    }
  }

  @override
  Future<Either<Failure, List<Story>>> getGeneratedStories({
    int limit = 10,
    int offset = 0,
  }) async {
    try {
      final user = SupabaseService.client.auth.currentUser;
      if (user == null) {
        return Left(ServerFailure('User not authenticated'));
      }

      final response = await SupabaseService.client
          .from('stories')
          .select()
          .eq('user_id', user.id)
          .order('updated_at', ascending: false)
          .range(offset, offset + limit - 1);

      return Right(response.map((row) => _mapSupabaseRowToStory(row)).toList());
    } catch (e) {
      return Left(ServerFailure('Failed to fetch story: ${e.toString()}'));
    }
  }

  Map<String, dynamic> _attributesToMap(Story story) {
    final a = story.attributes;
    return {
      'story_type': a.storyType,
      'theme': a.theme,
      'main_character_type': a.mainCharacterType,
      'story_setting': a.storySetting,
      'time_era': a.timeEra,
      'narrative_perspective': a.narrativePerspective,
      'language_style': a.languageStyle,
      'emotional_tone': a.emotionalTone,
      'narrative_style': a.narrativeStyle,
      'plot_structure': a.plotStructure,
      'story_length': a.storyLength,
      'references': a.references,
      'tags': a.tags,
      'characters': a.characters,
      'character_details': a.characterDetails,
      // keep the old scalar UI fields too if your UI depends on them
      'quotes': story.quotes,
      'trivia': story.trivia,
      'activity': story.activity,
      'scripture': story.scripture,
      'moral': story.lesson,
      'translations': a.translations,
    };
  }

  String _normalizeStoryText(String? value) {
    if (value == null || value.isEmpty) return '';
    return value
        .replaceAll('\\r\\n', '\n')
        .replaceAll('\\n', '\n')
        .replaceAll('\\r', '\n')
        .replaceAll('\r\n', '\n')
        .replaceAll('\r', '\n')
        .trim();
  }

  Story _mapSupabaseRowToStory(Map<String, dynamic> row) {
    final attr =
        (row['attributes'] as Map?)?.cast<String, dynamic>() ??
        <String, dynamic>{};
    final meta =
        (row['metadata'] as Map?)?.cast<String, dynamic>() ??
        <String, dynamic>{};
    final characterDetails =
        (attr['character_details'] as Map?)?.cast<String, dynamic>() ??
        <String, dynamic>{};

    return Story(
      id: row['id']!.toString(),
      authorId: row['user_id']?.toString(),
      title: row['title']?.toString() ?? 'Untitled Story',
      story: _normalizeStoryText(row['content']?.toString()),
      scripture:
          _normalizeStoryText(
            attr['scripture']?.toString() ?? meta['scripture']?.toString(),
          ).isNotEmpty
          ? _normalizeStoryText(
              attr['scripture']?.toString() ?? meta['scripture']?.toString(),
            )
          :
          'Scripture',
      quotes: _normalizeStoryText(
        attr['quotes']?.toString() ?? meta['quotes']?.toString(),
      ),
      trivia: _normalizeStoryText(
        attr['trivia']?.toString() ?? meta['trivia']?.toString(),
      ),
      activity: _normalizeStoryText(
        attr['activity']?.toString() ?? meta['activity']?.toString(),
      ),
      lesson: _normalizeStoryText(
        attr['moral']?.toString() ?? meta['lesson']?.toString(),
      ),
      attributes: StoryAttributes(
        storyType: attr['story_type']?.toString() ?? 'General',
        theme: attr['theme']?.toString() ?? 'Dharma (Duty)',
        mainCharacterType:
            attr['main_character_type']?.toString() ?? 'Protagonist',
        storySetting: attr['story_setting']?.toString() ?? 'Ancient India',
        timeEra: attr['time_era']?.toString() ?? 'Ancient',
        narrativePerspective:
            attr['narrative_perspective']?.toString() ?? 'Third Person',
        languageStyle:
            row['language']?.toString() ??
            attr['language_style']?.toString() ??
            'English',
        emotionalTone: attr['emotional_tone']?.toString() ?? 'Inspirational',
        narrativeStyle: attr['narrative_style']?.toString() ?? 'Narrative',
        plotStructure: attr['plot_structure']?.toString() ?? 'Linear',
        storyLength: attr['story_length']?.toString() ?? 'Medium ~1000 words',
        tags: (attr['tags'] as List<dynamic>? ?? const [])
            .map((tag) => tag.toString())
            .toList(),
        references: (attr['references'] is List)
            ? (attr['references'] as List<dynamic>)
                  .map((e) => e.toString())
                  .toList()
            : [attr['references']?.toString() ?? ''],
        characters: (attr['characters'] as List<dynamic>? ?? const [])
            .map((char) => char.toString())
            .toList(),
        characterDetails: characterDetails,
        translations: _parseTranslations(attr['translations']),
      ),
      imageUrl: row['image_url']?.toString(),
      createdAt: row['created_at'] != null
          ? DateTime.tryParse(row['created_at'].toString())
          : null,
      updatedAt: row['updated_at'] != null
          ? DateTime.tryParse(row['updated_at'].toString())
          : null,
      publishedAt: row['published_at'] != null
          ? DateTime.tryParse(row['published_at'].toString())
          : null,
      author: row['author']?.toString(),
      likes: (row['likes'] is int)
          ? row['likes'] as int
          : (row['likes'] as num?)?.toInt() ?? 0,
      views: (row['views'] is int)
          ? row['views'] as int
          : (row['views'] as num?)?.toInt() ?? 0,
      isFavorite: row['is_favourite'] as bool? ?? false,
      commentCount: (row['comment_count'] as num?)?.toInt() ?? 0,
      shareCount: (row['share_count'] as num?)?.toInt() ?? 0,
    );
  }

  Map<String, TranslatedStory> _parseTranslations(dynamic raw) {
    if (raw == null) return <String, TranslatedStory>{};

    if (raw is Map) {
      final out = <String, TranslatedStory>{};

      for (final entry in raw.entries) {
        final lang = entry.key.toString();
        final val = entry.value;

        if (val == null) continue;

        if (val is Map<String, dynamic>) {
          out[lang] = TranslatedStory.fromJson(val);
          continue;
        }
        if (val is Map) {
          out[lang] = TranslatedStory.fromJson(Map<String, dynamic>.from(val));
          continue;
        }

        if (val is String) {
          try {
            final decoded = jsonDecode(val);
            if (decoded is Map) {
              out[lang] = TranslatedStory.fromJson(
                Map<String, dynamic>.from(decoded),
              );
            }
          } catch (_) {}
        }
      }

      return out;
    }

    return <String, TranslatedStory>{};
  }

  @override
  Future<Either<Failure, String>> expandStory({
    required Story story,
    required int currentChapter,
    required String storyLanguage,
  }) async {
    try {
      final currentUserId = SupabaseService.client.auth.currentUser?.id;
      if (!_isStoryOwnedByUser(story, currentUserId)) {
        return Left(ServerFailure(_insightsOwnerOnlyMessage));
      }

      final result = await _remoteDataSource.interactWithStory(
        storyTitle: story.title,
        storyContent: story.story,
        interactionType: 'expand',
        characterName: null,
        currentChapter: currentChapter,
        storyLanguage: storyLanguage,
      );

      final chapterText = result['response']?.toString();
      if (chapterText == null || chapterText.trim().isEmpty) {
        return Left(ServerFailure('Empty expand response from server'));
      }

      return Right(chapterText);
    } catch (e) {
      return Left(
        ServerFailure(
          toUserFriendlyErrorMessage(e, fallback: 'Failed to expand story'),
        ),
      );
    }
  }

  @override
  Future<Either<Failure, Story>> regenerateStory({
    required Story original,
    required StoryPrompt prompt,
    required GeneratorOptions options,
  }) async {
    try {
      final result = await _remoteDataSource.generateStory(
        prompt: prompt,
        options: options,
      );

      final user = SupabaseService.client.auth.currentUser;
      final userRepo = UserRemoteDataSourceSupabase(SupabaseService.client);
      final author = await userRepo.getUserById(user!.id);
      final title = result['title'] as String? ?? 'Untitled Story';
      final storyContent = result['story'] as String? ?? '';
      final moral = result['moral'] as String? ?? '';
      final reference = result['reference'] as String? ?? '';
      final characters = (result['characters'] as List<dynamic>? ?? const [])
          .map((e) => e.toString())
          .toList();

      // Extract LLM-provided attributes (if any)
      final attributes =
          (result['attributes'] as Map?)?.cast<String, dynamic>() ??
          <String, dynamic>{};

      final scriptureFromAttributes =
          (attributes['references'] is List &&
              (attributes['references'] as List).isNotEmpty)
          ? (attributes['references'] as List).first.toString()
          : null;
      final scriptureFromResult = result['scripture'] as String?;

      final scripture = (scriptureFromAttributes?.trim().isNotEmpty ?? false)
          ? scriptureFromAttributes!.trim()
          : (scriptureFromResult?.trim().isNotEmpty ?? false)
          ? scriptureFromResult!.trim()
          : (prompt.scripture?.trim().isNotEmpty ?? false)
          ? prompt.scripture!.trim()
          : 'Unknown';

      final triviaFromLlm = (result['trivia'] as String?)?.trim() ?? '';
      final quotesFromLlm = (result['quotes'] as String?)?.trim() ?? '';
      final activityFromLlm = (result['activity'] as String?)?.trim() ?? '';

      final theme = prompt.theme ?? 'Dharma';

      final storyMap = {
        'id': original.id,
        'user_id': user.id,
        'title': title,
        'content': storyContent,
        'language': options.language.displayName,
        'metadata': {
          'scripture': scripture,
          'trivia': triviaFromLlm,
          'quotes': quotesFromLlm,
          'activity': activityFromLlm,
          'lesson': moral,
        },
        'attributes': {
          'quotes': quotesFromLlm.isNotEmpty
              ? quotesFromLlm
              : _getQuotes(theme),
          'trivia': triviaFromLlm.isNotEmpty
              ? triviaFromLlm
              : _getTrivia(scripture),
          'activity': activityFromLlm.isNotEmpty
              ? activityFromLlm
              : _getActivity(theme),
          'scripture': scripture,
          'theme': theme,
          'references':
              attributes['references'] ??
              (reference.isNotEmpty ? reference : scripture),
          'characters': attributes['characters'] ?? characters,
          'character_details': <String, dynamic>{}, // reset on regenerate
          'moral': moral.isNotEmpty ? moral : _getLesson(theme),
          'story_type': prompt.storyType,
          'main_character_type': prompt.mainCharacter,
          'story_setting': prompt.setting,
          'time_era': prompt.scriptureSubtype ?? scripture,
          'narrative_perspective': 'Third Person',
          'language_style': options.language.displayName,
          'emotional_tone': 'Inspiring',
          'narrative_style': options.format.displayName,
          'plot_structure':
              '${options.length.displayName} ${options.length.description}',
          'story_length':
              '${options.length.displayName} ${options.length.description}',
          'tags': <String>[],
          'translations': {
            languageNameToCode(options.language.displayName): TranslatedStory(
              title: title,
              story: storyContent,
              moral: moral,
              trivia: triviaFromLlm.isNotEmpty
                  ? triviaFromLlm
                  : _getTrivia(scripture),
              lang: languageNameToCode(options.language.displayName),
            ),
          },
        },
        'author_id': author.id,
        'author': author.displayName,
        'image_url': null,
        'updated_at': DateTime.now().toIso8601String(),
      };
      final response = await SupabaseService.client
          .from('stories')
          .update(storyMap)
          .eq('id', original.id)
          .select()
          .single();

      return Right(_mapSupabaseRowToStory(response));
    } catch (e) {
      return Left(
        ServerFailure(
          toUserFriendlyErrorMessage(e, fallback: 'Failed to regenerate story'),
        ),
      );
    }
  }

  @override
  Future<Either<Failure, Map<String, dynamic>>> getCharacterDetails({
    required Story story,
    required String characterName,
    required int currentChapter,
    required String storyLanguage,
  }) async {
    try {
      final currentUserId = SupabaseService.client.auth.currentUser?.id;
      if (!_isStoryOwnedByUser(story, currentUserId)) {
        return Left(ServerFailure(_insightsOwnerOnlyMessage));
      }

      final result = await _remoteDataSource.interactWithStory(
        storyTitle: story.title,
        storyContent: story.story,
        interactionType: 'characters',
        characterName: characterName,
        currentChapter: currentChapter,
        storyLanguage: storyLanguage,
      );

      // The endpoint returns the full character object (NOT wrapped in {response: ...}).
      if (result.isEmpty) {
        return Left(
          ServerFailure('Empty character details response from server'),
        );
      }

      return Right(result);
    } catch (e) {
      return Left(
        ServerFailure(
          toUserFriendlyErrorMessage(
            e,
            fallback: 'Failed to get character details',
          ),
        ),
      );
    }
  }

  // Helper methods ported for local generation of auxiliary fields
  String _getQuotes(String theme) {
    final quotes = {
      'Dharma (Duty)':
          '"It is better to perform one\'s own duty imperfectly than to master the duty of another." - Bhagavad Gita',
      'Karma (Action)':
          '"You have the right to work, but never to the fruit of work." - Bhagavad Gita',
      'Bhakti (Devotion)':
          '"Whatever you do, whatever you eat, whatever you offer or give away, do it as an offering to Me." - Bhagavad Gita',
      'Moksha (Liberation)':
          '"The soul is neither born, and nor does it die." - Bhagavad Gita',
      'Knowledge & Wisdom':
          '"There is no purifier equal to knowledge in this world." - Bhagavad Gita',
    };
    // Return a random default if theme matches none or generic
    return quotes[theme] ??
        '"Truth alone triumphs, not falsehood." - Mundaka Upanishad';
  }

  String _getTrivia(String scripture) {
    final trivia = {
      'Mahabharata':
          'The Mahabharata is one of the longest epic poems in the world, with over 100,000 shlokas (couplets).',
      'Ramayana':
          'The Ramayana was composed by Sage Valmiki, who is often called the "Adi Kavi" (first poet).',
      'Bhāgavata Purāṇa':
          'The Bhagavata Purana contains 18,000 verses and is considered the most popular of all Puranas.',
      'Upanishads':
          'The Upanishads are the philosophical core of the Vedas and form the basis of Vedanta philosophy.',
    };
    // Simple partial match check
    for (final key in trivia.keys) {
      if (scripture.contains(key)) return trivia[key]!;
    }
    return 'Ancient Indian scriptures were passed down orally for thousands of years before being written.';
  }

  String _getActivity(String theme) {
    return 'Reflect on how the theme of "$theme" manifests in your daily life. Journal about one instance where you practiced or witnessed this principle today.';
  }

  String _getLesson(String theme) {
    final lessons = {
      'Dharma (Duty)':
          'Understanding and fulfilling our duties without attachment to results leads to inner peace and spiritual growth.',
      'Karma (Action)':
          'Every action has consequences that shape our future. Act wisely and with pure intentions.',
      'Bhakti (Devotion)':
          'True devotion transforms every moment into a sacred offering, connecting us with the divine.',
      'Moksha (Liberation)':
          'Liberation comes through knowledge, devotion, and the realization of our true eternal nature.',
      'Knowledge & Wisdom':
          'Wisdom is not merely knowing facts, but understanding the deeper truths that guide righteous living.',
    };
    return lessons[theme] ??
        'Every story carries within it seeds of wisdom. Water these seeds with reflection, and watch understanding bloom.';
  }

  static const String _storyChatTable = 'story_chats';

  Future<bool> _isStoryBookmarkedByUser({
    required String storyId,
    required String userId,
  }) async {
    try {
      final row = await SupabaseService.client
          .from('bookmarks')
          .select('id')
          .eq('user_id', userId)
          .eq('bookmarkable_type', 'story')
          .eq('bookmarkable_id', storyId)
          .maybeSingle();
      return row != null;
    } catch (_) {
      return false;
    }
  }

  @override
  Future<Either<Failure, StoryChatConversation>> getOrCreateStoryChat({
    required Story story,
  }) async {
    try {
      final user = SupabaseService.client.auth.currentUser;
      if (user == null) {
        return Left(ServerFailure('User not authenticated'));
      }
      if (!_isStoryOwnedByUser(story, user.id)) {
        return Left(ServerFailure(_insightsOwnerOnlyMessage));
      }

      // Check Supabase for existing chat
      final existing = await SupabaseService.client
          .from(_storyChatTable)
          .select()
          .eq('story_id', story.id)
          .eq('user_id', user.id)
          .maybeSingle();

      if (existing != null) {
        // Found existing chat, cache and return
        final conversation = StoryChatConversation.fromSupabaseRow(existing);

        await repository.upsert<StoryChatConversationModel>(
          StoryChatConversationModel.fromDomain(conversation),
          policy: OfflineFirstUpsertPolicy.optimisticLocal,
        );

        return Right(conversation);
      }

      // Create new chat in Supabase
      final now = DateTime.now();
      final initial = StoryChatMessage(
        sender: 'bot',
        text:
            'Let\'s discuss "${story.title}". Ask me anything about the story, characters, themes, or events.',
        timestamp: now,
        storyContext: _buildStoryContext(story),
      );

      final insertBody = {
        'story_id': story.id,
        'user_id': user.id,
        'title': 'Chat about ${story.title}',
        'messages': [initial.toJson()],
      };

      final row = await SupabaseService.client
          .from(_storyChatTable)
          .insert(insertBody)
          .select()
          .single();

      final conversation = StoryChatConversation.fromSupabaseRow(row);

      // Cache to Brick
      await repository.upsert<StoryChatConversationModel>(
        StoryChatConversationModel.fromDomain(conversation),
        policy: OfflineFirstUpsertPolicy.optimisticLocal,
      );

      return Right(conversation);
    } catch (e) {
      return Left(
        ServerFailure(
          toUserFriendlyErrorMessage(e, fallback: 'Failed to load story chat'),
        ),
      );
    }
  }

  @override
  Future<Either<Failure, StoryChatConversation>> sendStoryChatMessage({
    required Story story,
    required StoryChatConversation conversation,
    required String message,
    required String language,
  }) async {
    try {
      final user = SupabaseService.client.auth.currentUser;
      if (user == null) {
        return Left(ServerFailure('User not authenticated'));
      }
      if (!_isStoryOwnedByUser(story, user.id)) {
        return Left(ServerFailure(_insightsOwnerOnlyMessage));
      }

      final now = DateTime.now();

      final updatedMessages = <StoryChatMessage>[
        ...conversation.messages,
        StoryChatMessage(sender: 'user', text: message, timestamp: now),
      ];

      final botText = await _remoteDataSource.chat(
        messages: updatedMessages.map((m) => m.toJson()).toList(),
        mode: 'story_scholar',
        storyContext: _buildStoryContext(story),
        language: language,
      );

      final withBot = <StoryChatMessage>[
        ...updatedMessages,
        StoryChatMessage(
          sender: 'bot',
          text: botText,
          timestamp: DateTime.now(),
        ),
      ];

      final updateBody = {
        'messages': withBot.map((m) => m.toJson()).toList(),
        'updated_at': DateTime.now().toIso8601String(),
      };

      final row = await SupabaseService.client
          .from(_storyChatTable)
          .update(updateBody)
          .eq('id', conversation.id)
          .select()
          .single();

      final updated = StoryChatConversation.fromSupabaseRow(row);

      // Update cache
      await repository.upsert<StoryChatConversationModel>(
        StoryChatConversationModel.fromDomain(updated),
        policy: OfflineFirstUpsertPolicy.optimisticLocal,
      );

      return Right(updated);
    } catch (e) {
      return Left(
        ServerFailure(
          toUserFriendlyErrorMessage(e, fallback: 'Failed to send message'),
        ),
      );
    }
  }

  @override
  Future<Either<Failure, TranslatedStory>> translateStory({
    required Story story,
    required String targetLang,
  }) async {
    try {
      final data = await _remoteDataSource.translateStory(
        title: story.title,
        content: story.story,
        moral: story.lesson,
        trivia: story.trivia.isNotEmpty ? story.trivia : null,
        targetLang: targetLang,
      );

      // story.attributes.translations.addEntries([
      //   MapEntry(
      //     targetLang,
      //     TranslatedStory(
      //       title: data['title']?.toString() ?? 'Untitled Story',
      //       story: data['story']?.toString() ?? '',
      //       moral: data['moral']?.toString() ?? '',
      //       lang: targetLang,
      //     ),
      //   ),
      // ]);

      // final updateBody = {
      //   'attributes': {
      //     'translations': story.attributes.translations.map(
      //       (key, value) => MapEntry(key, value.toJson()),
      //     ),
      //   },
      //   'updated_at': DateTime.now().toIso8601String(),
      // };

      // final response = await SupabaseService.client
      //     .from('stories')
      //     .update(updateBody)
      //     .eq('id', story.id)
      //     .select()
      //     .single();

      return Right(TranslatedStory.fromJson(data));
    } catch (e) {
      return Left(ServerFailure('Failed to translate: $e'));
    }
  }

  String languageNameToCode(String name) {
    return LanguageVoiceResolver.languageCodeFromAny(name);
  }

  String languageCodeToName(String name) {
    return LanguageVoiceResolver.displayNameForCode(name);
  }

  bool _isStoryOwnedByUser(Story story, String? userId) {
    if (userId == null || userId.isEmpty) return false;
    return story.authorId == userId || story.authorUser?.id == userId;
  }

  Map<String, dynamic> _buildStoryContext(Story story) {
    return {
      'title': story.title,
      'story': story.story,
      'scripture': story.scripture,
      'theme': story.attributes.theme,
      'moral': story.lesson,
      'characters': story.attributes.characters,
    };
  }
}
