const Map<String, Map<String, dynamic>> storyOptions = {
  'storyType': {
    "types": [
      "Epic Adventure",
      "Moral Tale",
      "Devotional Story",
      "Philosophical Journey",
      "Historical Legend",
      "Folk Tale",
      "Divine Intervention",
      "Warrior Saga",
      "Divine Romance",
      "Creation Myth",
      "Spiritual Transformation",
      "Sacred Quest",
      "Divine Tragedy",
      "Divine Comedy",
      "Mystical Mystery",
      "Legendary Tale",
      "Divine Fable",
      "Divine Parable",
      "Divine Prophecy",
      "Divine Revenge",
      "Divine Sacrifice",
      "Animal Fable",
      "Wisdom Tale",
      "Court Story",
      "Riddle Story",
      "Trickster Tale",
      "Origin Story",
      "Heroic Journey",
      "Redemption Story",
      "Coming of Age",
      "Battle Epic",
    ],
  },
  'theme': {
    "types": [
      "Dharma (Duty)",
      "Karma (Action)",
      "Bhakti (Devotion)",
      "Moksha (Liberation)",
      "Sacrifice & Loyalty",
      "Knowledge & Wisdom",
      "Family & Relationships",
      "Power & Leadership",
      "Spiritual Transformation",
      "Divine Justice",
      "Destiny & Fate",
      "Cosmic Harmony",
      "Sacred Traditions",
      "Divine Redemption",
      "Eternal Truths",
      "Cleverness & Wit",
      "Humility & Pride",
      "Friendship & Trust",
      "Courage & Fear",
      "Greed & Contentment",
      "Truth & Deception",
      "Compassion & Cruelty",
      "Unity & Division",
      "Patience & Haste",
      "Good vs Evil",
      "Inner Peace",
      "Self-Discovery",
      "Forgiveness",
      "Perseverance",
      "Honor & Shame",
      "Duty vs Desire",
      "Faith Under Trial",
      "Wisdom in Adversity",
      "Service & Sacrifice",
      "Truthful Leadership",
      "Divine Grace",
      "Ethical Courage",
      "Balance of Nature",
      "Discipline & Restraint",
      "Unity in Diversity",
      "Righteous Victory",
      "Humane Governance",
      "Mindfulness & Presence",
      "Justice with Compassion",
      "Loyalty & Betrayal",
    ],
  },
  'mainCharacter': {
    "types": [
      "Divine Being",
      "Sage/Rishi",
      "Warrior/Kshatriya",
      "Royal Family Member",
      "Devoted Seeker",
      "Common Person",
      "Celestial Being",
      "Divine Animal",
      "Asura/Rakshasa",
      "Temple Priest",
      "Mystic/Yogi",
      "Divine Guardian",
      "Spiritual Entity",
      "Elemental Spirit",
      "Mythical Creature",
      "Divine Avatar",
      "Goddess/Devi",
      "Demoness/Rakshasi",
      "Epic Hero",
      "Epic Villain",
      "Divine Mentor",
      "Clever Courtier",
      "Wise Minister",
      "Merchant/Trader",
      "Farmer/Villager",
      "Student/Disciple",
      "Forest Hermit",
      "Traveling Bard",
      "Royal Guard",
      "Palace Servant",
      "Clever Child",
      "Elderly Wise Person",
      "Talking Animal",
      "Magical Being",
      "Ghost/Spirit",
    ],
  },
  'setting': {
    "types": [
      "Sacred Forest",
      "Ancient Kingdom",
      "Sage's Ashram",
      "Epic Battlefield",
      "Celestial Realm",
      "Holy Pilgrimage Site",
      "Ancient Village",
      "Royal Palace",
      "Sacred Mountain",
      "Holy River",
      "Ancient Temple",
      "Mystical Cave",
      "Sacred Island",
      "Spiritual Desert",
      "Royal Court",
      "Marketplace",
      "Gurukul School",
      "Monastery",
      "Ancient Library",
      "Enchanted Garden",
      "Riverside Ghat",
      "Mountain Pass",
      "Desert Oasis",
      "Jungle Clearing",
      "Ancient City",
      "Hermit's Hut",
      "Palace Gardens",
      "Village Square",
      "Sacred Grove",
      "Crossroads",
      "Ancient Ruins",
      "Magical Realm",
      "Underwater Kingdom",
      "Sky Palace",
    ],
  },
  'scripture': {
    "types": [
      'Epics (Itihasa)',
      'Core Scriptures (Shruti)',
      'Mahāpurāṇas (Smriti)',
      'Upapurāṇas',
      'Wisdom & Other Tales',
    ],
    "subtypes": {
      'Epics (Itihasa)': ['Ramayana', 'Mahabharata', 'Ramcharitmanas'],
      'Core Scriptures (Shruti)': ['Vedas', 'Upanishads'],
      'Mahāpurāṇas (Smriti)': [
        'Brahma Purāṇa',
        'Padma Purāṇa',
        'Viṣṇu Purāṇa',
        'Śiva Purāṇa',
        'Bhāgavata Purāṇa',
        'Nārada Purāṇa',
        'Mārkaṇḍeya Purāṇa',
        'Agni Purāṇa',
        'Bhaviṣya Purāṇa',
        'Brahma Vaivarta Purāṇa',
        'Liṅga Purāṇa',
        'Varāha Purāṇa',
        'Skanda Purāṇa',
        'Vāmana Purāṇa',
        'Kūrma Purāṇa',
        'Matsya Purāṇa',
        'Garuda Purāṇa',
        'Brahmāṇḍa Purāṇa',
        'Sanatkumāra Purāṇa',
      ],
      'Upapurāṇas': [
        'Narasimha Purāṇa',
        'Nandī Purāṇa',
        'Śiva Rahasya Purāṇa',
        'Durvāsā Purāṇa',
        'Kapila Purāṇa',
        'Bhārata Purāṇa',
        'Sāmba Purāṇa',
        'Saurapurāṇa',
        'Āditya Purāṇa',
        'Maheshwara Purāṇa',
        'Kalki Purāṇa',
        'Mahābhāgavata Purāṇa',
        'Taraṇi Purāṇa',
        'Vishnudharmottara Purāṇa',
        'Bṛhaddharma Purāṇa',
        'Devī Bhāgavata Purāṇa',
      ],
      'Wisdom & Other Tales': [
        'Panchatantra',
        'Hitopadesha',
        'Jataka Tales',
        'Vikram Betal',
        'Tenali Rama',
        'Amar Chitra Katha',
        'Local Temple Narratives',
      ],
    },
  },
};
