-- Seed Hindu festivals for Indian Festivals section
INSERT INTO public.hindu_festivals (
  name, slug, short_description, description, when_celebrated, when_details,
  where_celebrated, how_celebrated, history, significance, scriptures_related,
  image_url, order_index
) VALUES
(
  'Diwali',
  'diwali',
  'Festival of Lights celebrating the victory of light over darkness.',
  'Diwali, or Deepavali, is one of the most important Hindu festivals, symbolizing the victory of light over darkness and good over evil. It is celebrated with lamps, rangoli, sweets, and family gatherings.',
  'Kartik Amavasya',
  'Usually October or November (lunar calendar)',
  'Pan-India; Nepal, Sri Lanka, Singapore, Malaysia, and diaspora worldwide',
  'Lighting diyas (oil lamps), rangoli, Lakshmi puja, bursting firecrackers, exchanging sweets and gifts, cleaning homes.',
  'Diwali is linked to the return of Lord Rama to Ayodhya after 14 years of exile (Ramayana), and to the victory of Lord Krishna over Narakasura. In some regions it marks the day Goddess Lakshmi emerged from the churning of the ocean.',
  'Spiritual renewal, prosperity (Lakshmi), and the triumph of dharma. It also marks the Hindu New Year in some regions.',
  'Ramayana, Bhagavata Purana',
  NULL,
  1
),
(
  'Holi',
  'holi',
  'Festival of Colours celebrating spring and the divine love of Radha and Krishna.',
  'Holi is a vibrant spring festival where people throw coloured powder and water, sing and dance. It celebrates the eternal love of Radha and Krishna and the victory of devotion over evil.',
  'Phalguna Purnima',
  'Usually March (full moon day)',
  'Pan-India; Nepal and diaspora',
  'Playing with coloured powder (gulal) and water, bonfire on Holika Dahan eve, singing, dancing, sweets like gujiya and thandai.',
  'The festival commemorates the story of Prahlad and Holika: the demon king Hiranyakashipu tried to kill his devotee son Prahlad, but Holika (who was immune to fire) was burnt while Prahlad was saved by Vishnu. Holi also celebrates the divine play of Radha and Krishna in Vrindavan.',
  'Joy, forgiveness, and the arrival of spring. It signifies the victory of devotion and the end of winter.',
  'Bhagavata Purana',
  NULL,
  2
),
(
  'Navratri',
  'navratri',
  'Nine nights of worship of the Divine Mother in her various forms.',
  'Navratri is a nine-night festival dedicated to Goddess Durga and her nine forms. It combines fasting, dance (Garba, Dandiya), and devotional music across India.',
  'Ashvin (Sharad) / Chaitra',
  'Twice a year: post-monsoon (Sept–Oct) and spring (Mar–Apr)',
  'Pan-India; Gujarat and West Bengal have especially grand celebrations',
  'Fasting, Garba and Dandiya Raas (Gujarat), Durga Puja (East), Kolu (South), nightly puja and aarti.',
  'Navratri marks the battle between Goddess Durga and the buffalo demon Mahishasura, culminating in his defeat on Vijayadashami. It also honours the nine forms of Shakti.',
  'Victory of divine power over evil; devotion to the Mother Goddess; harvest and renewal.',
  'Devi Mahatmyam, Markandeya Purana',
  NULL,
  3
),
(
  'Durga Puja',
  'durga-puja',
  'Celebration of Goddess Durga''s victory over the buffalo demon Mahishasura.',
  'Durga Puja is a major festival in East India (especially West Bengal) where elaborately crafted pandals house idols of Goddess Durga. It spans five days of worship, music, and cultural events.',
  'Ashvin (Bengali calendar)',
  'Usually September–October; coincides with Navratri',
  'West Bengal, Assam, Odisha, Bihar, Tripura; diaspora',
  'Pandal visits, idol immersion (Visarjan), dhak drums, dhunuchi dance, bhog (prasad), new clothes and family gatherings.',
  'The festival celebrates the ten-day battle between Durga and Mahishasura, ending with her victory on Vijayadashami. It also honours the annual visit of the goddess to her earthly home.',
  'Triumph of good over evil; honouring Shakti and feminine divinity; community and culture.',
  'Devi Mahatmyam',
  NULL,
  4
),
(
  'Ganesh Chaturthi',
  'ganesh-chaturthi',
  'Birthday of Lord Ganesha, the remover of obstacles.',
  'Ganesh Chaturthi marks the birth of Lord Ganesha. Idols are installed at home and in public pandals, worshipped for 1–11 days, then immersed in water.',
  'Bhadrapada Shukla Chaturthi',
  'Usually August–September',
  'Maharashtra, Karnataka, Goa, Telangana; widely in North and South India',
  'Installing clay idols, daily puja and aarti, modak (sweet), singing, and visarjan (immersion) in rivers or sea.',
  'According to legend, Goddess Parvati created Ganesha to guard her door. When Shiva beheaded him, Parvati was distraught; Shiva restored him with an elephant head. The festival celebrates his birth and wisdom.',
  'New beginnings, wisdom, and removal of obstacles. Ganesha is invoked before any important undertaking.',
  'Ganesha Purana, Shiva Purana',
  NULL,
  5
),
(
  'Makar Sankranti',
  'makar-sankranti',
  'Harvest festival marking the sun''s transition into Capricorn.',
  'Makar Sankranti is a harvest festival celebrated when the sun enters the zodiac sign of Capricorn (Makar). It is known by different names across India: Pongal, Uttarayan, Khichdi, etc.',
  '14 January (solar; fixed date)',
  '14 January every year',
  'Pan-India: Pongal (Tamil Nadu), Uttarayan (Gujarat), Magh Bihu (Assam), Lohri (North)',
  'Flying kites, bonfires (Lohri), Pongal cooking, holy dips in Ganga, donating til and jaggery, feasts.',
  'The festival marks the end of winter and the beginning of the sun''s northward journey (Uttarayan). It is associated with the end of the inauspicious month and the harvest.',
  'Thanksgiving for harvest; auspicious new phase; unity and charity.',
  'References in Mahabharata (Bhishma waited for Uttarayan to leave his body)',
  NULL,
  6
),
(
  'Raksha Bandhan',
  'raksha-bandhan',
  'Bond between brothers and sisters; sisters tie a protective thread (rakhi) on brothers.',
  'On Raksha Bandhan, sisters tie a sacred thread (rakhi) on their brothers'' wrists and brothers promise protection. It celebrates sibling love and duty.',
  'Shravan Purnima',
  'Usually August (full moon)',
  'Pan-India and Nepal',
  'Tying rakhi, exchange of gifts, sweets, family gatherings. In some regions, priests tie rakhis to devotees.',
  'The festival has roots in the bond between Krishna and Draupadi (Mahabharata) and the legend of King Bali and Goddess Lakshmi. It symbolises the brother''s vow to protect the sister.',
  'Sibling love, protection, and familial duty (dharma).',
  'Mahabharata, Bhavishya Purana',
  NULL,
  7
),
(
  'Janmashtami',
  'janmashtami',
  'Birth anniversary of Lord Krishna.',
  'Janmashtami celebrates the birth of Lord Krishna in Mathura. Devotees fast, sing bhajans, and re-enact Krishna''s childhood (Dahi Handi in Maharashtra).',
  'Krishna Paksha Ashtami, Bhadrapada',
  'Usually August–September',
  'Pan-India; major celebrations in Mathura, Vrindavan, Gujarat, Maharashtra',
  'Fasting until midnight, night vigils, bhajans, Dahi Handi (breaking curd pot), Jhulanotsav (swing festival), baby Krishna cradle.',
  'Krishna was born at midnight in a prison in Mathura to Devaki and Vasudeva, to end the tyranny of Kansa. He was secretly taken to Gokul and raised by Yashoda and Nanda.',
  'Devotion to Krishna; celebration of divine play (leela) and the triumph of good over evil.',
  'Bhagavata Purana',
  NULL,
  8
),
(
  'Maha Shivaratri',
  'maha-shivaratri',
  'Great Night of Shiva; night of worship and fasting.',
  'Maha Shivaratri is dedicated to Lord Shiva. Devotees observe a day-long fast and stay awake at night, offering bilva leaves, milk, and water to the Shiva Lingam.',
  'Phalguna Krishna Chaturdashi',
  'Usually February–March (14th night of waning moon)',
  'Pan-India; major at Shiva temples (e.g. Varanasi, Somnath)',
  'Fasting, night-long vigil, Shiva Lingam abhishekam (milk, water, bilva), chanting Om Namah Shivaya, meditation.',
  'Shivaratri is associated with the night of Shiva''s cosmic dance (Tandava) and the marriage of Shiva and Parvati. It is also when Shiva drank the poison from the churning of the ocean to save the world.',
  'Overcoming darkness and ignorance; devotion to Shiva; austerity and self-discipline.',
  'Shiva Purana, Linga Purana',
  NULL,
  9
),
(
  'Onam',
  'onam',
  'Harvest festival of Kerala celebrating the homecoming of King Mahabali.',
  'Onam is the biggest festival of Kerala. It commemorates the annual visit of the asura king Mahabali to his people. Celebrations include pookalam (flower rangoli), boat races, and the Onam sadya (feast).',
  'Chingam (Malayalam calendar)',
  'Usually August–September',
  'Kerala; Malayali diaspora',
  'Pookalam (flower carpets), Onam sadya (banana leaf feast), Vallam Kali (boat races), Pulikali (tiger dance), Thiruvathira Kali.',
  'King Mahabali was a generous ruler. When Vamana (Vishnu) sent him to the netherworld, he was granted a boon to visit his people once a year. Onam marks this homecoming.',
  'Harvest, prosperity, and the ideal of a just ruler. Unity and cultural pride for Keralites.',
  'Bhagavata Purana, Vamana avatar',
  NULL,
  10
),
(
  'Pongal',
  'pongal',
  'Tamil harvest festival thanking the sun and farm animals.',
  'Pongal is a four-day Tamil harvest festival. The main day involves boiling rice with milk and jaggery (Pongal) as an offering to the Sun God. It also honours cattle and nature.',
  'Thai (Tamil month)',
  'Usually mid-January (around Makar Sankranti)',
  'Tamil Nadu, Sri Lanka, Tamil diaspora',
  'Cooking Pongal in earthen pots, decorating cattle, Kolam (rangoli), Jallikattu (in some areas), visiting temples and family.',
  'Pongal has ancient agrarian roots. The name means "overflowing" and signifies abundance. It is linked to the sun''s northward journey and thanksgiving for the harvest.',
  'Thanksgiving to Sun, earth, and cattle; prosperity and renewal; Tamil identity.',
  'References in Sangam literature',
  NULL,
  11
)
ON CONFLICT (slug) DO NOTHING;
