-- Additional Hindu festivals for Indian Festivals section
INSERT INTO public.hindu_festivals (
  name, slug, short_description, description, when_celebrated, when_details,
  where_celebrated, how_celebrated, history, significance, scriptures_related,
  image_url, order_index
) VALUES
(
  'Chhath Puja',
  'chhath-puja',
  'Ancient Vedic festival dedicated to the Sun God and Chhathi Maiya.',
  'Chhath Puja is a four-day festival where devotees offer arghya to the rising and setting sun. It is especially popular in Bihar, Jharkhand, Uttar Pradesh, and Nepal. Fasting and standing in water are key rituals.',
  'Kartik Shukla Shashthi',
  'Usually October–November (6 days after Diwali)',
  'Bihar, Jharkhand, Uttar Pradesh, Nepal; Terai region',
  'Nahay khay, Kharna, Sandhya Arghya (evening offering), Usha Arghya (morning offering). Devotees fast and offer prasad of thekua, fruits, and coconut to the sun.',
  'Chhath is mentioned in the Rig Veda and has roots in the Mahabharata (Draupadi and the Pandavas observed it). It honours Surya and Shashthi (Chhathi Maiya), the goddess who protects children.',
  'Gratitude to the Sun for life and harvest; purity, discipline, and devotion; family well-being.',
  'Rig Veda, Mahabharata',
  NULL,
  12
),
(
  'Vasant Panchami',
  'vasant-panchami',
  'Spring festival dedicated to Goddess Saraswati and the onset of spring.',
  'Vasant Panchami marks the arrival of spring. It is dedicated to Goddess Saraswati (knowledge, music, arts). People wear yellow, fly kites, and students seek blessings for learning.',
  'Magha Shukla Panchami',
  'Usually January–February',
  'Pan-India; especially North and East India',
  'Wearing yellow clothes, Saraswati puja in schools and homes, offering flowers and sweets, kite flying, starting new learning (Akshar Abhyas).',
  'The day is associated with the birth or awakening of Saraswati. It also marks the end of winter and the beginning of the harvest season in some regions.',
  'Knowledge, wisdom, and the arts; auspicious start for education; celebration of spring.',
  'References in Puranas and regional traditions',
  NULL,
  13
),
(
  'Ugadi',
  'ugadi',
  'New Year for the people of Karnataka, Andhra Pradesh, and Telangana.',
  'Ugadi (Yugadi) marks the first day of the Hindu lunisolar calendar (Chaitra). It is celebrated with special foods like Ugadi pachadi (six tastes), new clothes, and temple visits.',
  'Chaitra Shukla Pratipada',
  'Usually March–April',
  'Karnataka, Andhra Pradesh, Telangana, Maharashtra (as Gudi Padwa)',
  'Ugadi pachadi (sweet, sour, bitter, salty, tangy, spicy), oil bath, new clothes, rangoli, mango leaves on doorways, temple visits, and family gatherings.',
  'Ugadi signifies the start of a new cycle. The pachadi represents the mix of experiences in life. The festival is linked to Brahma''s creation of the universe.',
  'New beginnings; acceptance of life''s varied experiences; cultural identity for Deccan states.',
  'References in almanacs and regional texts',
  NULL,
  14
),
(
  'Rama Navami',
  'rama-navami',
  'Birth anniversary of Lord Rama, the seventh avatar of Vishnu.',
  'Rama Navami celebrates the birth of Lord Rama in Ayodhya. Devotees observe fasts, read the Ramayana, and visit temples. In some places, processions and re-enactments take place.',
  'Chaitra Shukla Navami',
  'Usually March–April (9th day of Chaitra)',
  'Pan-India; major in Ayodhya, Rameswaram, Bhadrachalam',
  'Fasting, Ramayana recitation, bhajans, temple visits, charity, and in some regions chariot processions (Rath Yatra).',
  'Lord Rama was born to King Dasharatha and Queen Kaushalya in Ayodhya. The day marks the victory of dharma and the ideal king.',
  'Devotion to Rama; upholding dharma and righteousness; ideal leadership and family values.',
  'Ramayana, Valmiki Ramayana',
  NULL,
  15
),
(
  'Karwa Chauth',
  'karwa-chauth',
  'North Indian festival where married women fast for the longevity of their husbands.',
  'On Karwa Chauth, married women observe a nirjala (without water) fast from sunrise to moonrise. They break the fast after sighting the moon and performing a small puja.',
  'Kartik Krishna Chaturthi',
  'Usually October (4th day after full moon)',
  'North India: Rajasthan, Uttar Pradesh, Punjab, Haryana, Gujarat; diaspora',
  'Day-long nirjala fast, sargi (pre-dawn meal), applying mehndi, wearing new clothes, evening puja, breaking fast after moon sighting.',
  'The festival has roots in the story of Queen Veervati and the tale of Savitri and Satyavan. It symbolises a wife''s devotion and prayer for her husband''s well-being.',
  'Marital devotion; solidarity among women; prayer for spouse''s long life.',
  'Mahabharata (Savitri-Satyavan), regional folklore',
  NULL,
  16
),
(
  'Mahalaya',
  'mahalaya',
  'Beginning of Devi Paksha; invocation of ancestors and the Goddess.',
  'Mahalaya marks the start of the Pitru Paksha (ancestor fortnight) and in Bengal the beginning of Devi Paksha, leading to Durga Puja. It is the day to invoke ancestors and invite Goddess Durga.',
  'Amavasya before Ashvin Navratri',
  'Usually September (about a week before Durga Puja)',
  'West Bengal, Odisha, Assam; Bengali diaspora',
  'Tarpan (offerings to ancestors), listening to Mahalaya recitation and songs (e.g. “Mahishasura Mardini”), visiting temples, and beginning Durga Puja preparations.',
  'Mahalaya is when the goddess is believed to descend to earth. The “Mahishasura Mardini” programme is a cultural staple. It also honours forefathers through tarpan.',
  'Invoking the Goddess; honouring ancestors; start of the festive season.',
  'Devi Mahatmyam, Markandeya Purana',
  NULL,
  17
),
(
  'Vijayadashami',
  'vijayadashami',
  'Victory of good over evil; end of Navratri and Durga Puja.',
  'Vijayadashami (Dussehra) marks the victory of Rama over Ravana and of Durga over Mahishasura. In North India effigies of Ravana are burnt; in the East it is the last day of Durga Puja with immersion.',
  'Ashvin Shukla Dashami',
  'Usually September–October (10th day of Navratri)',
  'Pan-India; Ravan Dahan in North, Durga Visarjan in East',
  'Ravan Dahan (burning effigies), Durga idol immersion, Shami puja, starting new ventures (Vidyarambham in Kerala), exchanging leaves (apta) as gold.',
  'The day Rama defeated Ravana (Ramayana) and Durga defeated Mahishasura. It is considered auspicious for new beginnings.',
  'Victory of dharma over adharma; auspicious start for work and learning.',
  'Ramayana, Devi Mahatmyam',
  NULL,
  18
)
ON CONFLICT (slug) DO NOTHING;
