-- Seed 20+ prominent Indian fabric hubs with rich English-first details.
-- Image URLs follow the recommended storage convention:
-- fabric-hubs/{slug}/cover.jpg

INSERT INTO public.fabric_hubs (
    id, slug, name, region, state, latitude, longitude,
    fabric_name, short_description, about_place_and_fabric, history,
    cultural_significance, weaving_process, motifs_and_design,
    care_and_authenticity, best_buying_season, cover_image_url, gallery_urls,
    discussion_site_id, sort_order, is_published
) VALUES
('b8a9ef95-4894-49bf-bafb-c88831f8fa01','kanchipuram-silk','Kanchipuram','Tamil Nadu','Tamil Nadu',12.8342,79.7036,
 'Kanchipuram Silk','Heavy mulberry silk sarees with zari borders and temple-inspired geometry.',
 'Kanchipuram is one of India''s most respected silk weaving centers, known for durable body-border contrast and ceremonial drapes.',
 'Temple patronage and hereditary weaving streets shaped the town''s weaving identity over centuries.',
 'Bridal, festive, and ritual wardrobes across South India rely on Kanchipuram silk as a heritage marker.',
 'Traditional pit looms, mulberry yarn preparation, and zari integration are managed by specialized artisan teams.',
 'Checks, temple gopuram borders, and contrast pallus are signature visual elements.',
 'Check silk weight, zari authenticity, and weaving finish from certified outlets.',
 'October-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/kanchipuram-silk/cover.jpg',
 ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/kanchipuram-silk/gallery/1.jpg'],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a01',1,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa02','banarasi-silk','Varanasi','Uttar Pradesh','Uttar Pradesh',25.3176,82.9739,
 'Banarasi Silk','Fine brocade silk with zari-rich wedding and ceremonial repertoire.',
 'Varanasi weaving combines drawloom traditions, floral buta layouts, and brocade craftsmanship.',
 'Guild traditions, court demand, and pilgrimage commerce made Banarasi weaving globally recognized.',
 'Banarasi textiles are central to trousseau culture and heirloom collections.',
 'Silk warping, jacquard setup, and metallic thread integration require high artisan coordination.',
 'Jangla, kalga-bel, and intricate jaal motifs are recurring design signatures.',
 'Look for weave density, reverse-side quality, and GI-linked labeling.',
 'November-March',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/banarasi-silk/cover.jpg',
 ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/banarasi-silk/gallery/1.jpg'],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a02',2,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa03','bhagalpur-tussar','Bhagalpur','Bihar','Bihar',25.2500,87.0000,
 'Bhagalpuri Tussar Silk','Wild silk textures known for earthy sheen and breathable drape.',
 'Bhagalpur is a major tussar cluster blending cocoon-based sericulture with weaving households.',
 'Regional silk trade evolved through river routes and local weaving communities.',
 'Tussar apparel is popular for lightweight ceremonial and contemporary formal wear.',
 'Reeling, spinning, and loom finishing are distributed across artisanal micro-units.',
 'Subtle stripes, natural tones, and hand-printed overlays are common aesthetics.',
 'Verify fiber composition and buy from cooperative/state-authorized channels.',
 'September-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/bhagalpur-tussar/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a03',3,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa04','pochampally-ikat','Pochampally','Telangana','Telangana',17.5200,78.7500,
 'Pochampally Ikat','Tie-and-dye yarn resist work in silk and cotton with geometric precision.',
 'Pochampally is a landmark ikat cluster where pre-dyed warp/weft planning drives pattern clarity.',
 'Cooperative-led weaving expansion and GI recognition strengthened market visibility.',
 'Ikat remains a strong identity textile for festive and premium everyday wear.',
 'Yarn tying, resist dyeing, and planned loom alignment define the craft process.',
 'Diamonds, chevrons, and repeat geometry are signature visual identities.',
 'Confirm color fastness and edge finishing before purchase.',
 'October-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/pochampally-ikat/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a04',4,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa05','surat-textiles','Surat','Gujarat','Gujarat',21.1702,72.8311,
 'Surat Textile Hub','Large-scale weaving, dyeing, and distribution center with traditional continuity.',
 'Surat combines legacy textile trade with modern manufacturing and nationwide distribution links.',
 'Historic mercantile routes positioned Surat as a major cloth marketplace.',
 'Its wholesale ecosystem influences saree and dress-material markets across India.',
 'Powerloom and value-chain specialization dominate production cycles.',
 'Printed sarees, jacquard blends, and occasionwear textiles are widely traded.',
 'Prefer verified government/co-op channels when sourcing traditional segments.',
 'October-March',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/surat-textiles/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a05',5,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa06','chanderi-weave','Chanderi','Madhya Pradesh','Madhya Pradesh',24.7160,78.1387,
 'Chanderi','Lightweight translucent weave in silk-cotton blends.',
 'Chanderi fabrics are known for airy texture, elegant drape, and fine hand-feel.',
 'Royal patronage and artisan guilds sustained Chanderi through medieval and modern periods.',
 'Used in formal ethnic wear and refined festive collections.',
 'Fine-count warp and weft handling creates its hallmark transparency.',
 'Butis, coin motifs, and delicate zari highlights are common.',
 'Avoid harsh washing; prefer dry-clean for zari variants.',
 'November-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/chanderi-weave/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a06',6,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa07','maheshwari-weave','Maheshwar','Madhya Pradesh','Madhya Pradesh',22.1764,75.5879,
 'Maheshwari','Reversible-border sarees in silk-cotton with crisp stripes/checks.',
 'Maheshwar''s weaving ecosystem blends utility and ceremonial aesthetics.',
 'The craft expanded under local royal encouragement and cooperative movements.',
 'Favored for lightweight elegance and daily-to-festive versatility.',
 'Contrast-border planning and loom precision produce reversible edge identity.',
 'Narmada-inspired borders and geometric pallus are classic.',
 'Store folded with tissue to protect zari or dyed sections.',
 'September-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/maheshwari-weave/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a07',7,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa08','patan-patola','Patan','Gujarat','Gujarat',23.8500,72.1200,
 'Patan Patola','Double ikat silk with mathematically aligned motifs.',
 'Patan Patola is one of India''s most intricate resist-dyed silk traditions.',
 'Historically associated with elite patronage and temple-linked gifting.',
 'Considered heirloom textile due to rarity and labor intensity.',
 'Both warp and weft are resist-dyed before weaving, demanding exact alignment.',
 'Elephants, parrots, and geometric grids are iconic motifs.',
 'Authenticate through reputed family workshops and GI-traceable channels.',
 'October-March',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/patan-patola/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a08',8,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa09','paithani-yeola','Yeola','Maharashtra','Maharashtra',20.0420,74.4900,
 'Paithani','Rich silk sarees with peacock and lotus zari pallus.',
 'Yeola is a major center preserving Paithani weaving techniques.',
 'Paithani evolved through Deccan court and trade influences.',
 'Popular in Maharashtrian ceremonial and bridal contexts.',
 'Handloom weaving emphasizes pallu artistry and zari precision.',
 'Peacock, asawali, and lotus motifs define premium pieces.',
 'Protect from moisture and direct sunlight to preserve zari.',
 'October-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/paithani-yeola/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a09',9,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa10','sambalpuri-ikat','Sambalpur','Odisha','Odisha',21.4669,83.9812,
 'Sambalpuri Ikat','Bandha tie-dye craft in cotton and silk with narrative motifs.',
 'Sambalpuri textiles combine strong color language with regional symbolism.',
 'Bandha weaving traditions are linked to local caste and cooperative structures.',
 'Widely worn in Odisha festivals and state ceremonies.',
 'Yarn resist dyeing followed by loom precision creates motif clarity.',
 'Shankha, chakra, and floral geometry are recurring motifs.',
 'Buy from state emporia/cooperatives for authenticity.',
 'October-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/sambalpuri-ikat/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a10',10,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa11','baluchari-bishnupur','Bishnupur','West Bengal','West Bengal',23.0676,87.3160,
 'Baluchari','Narrative silk weaving with figurative pallus and ornate borders.',
 'Bishnupur preserves Baluchari traditions with storytelling-rich motifs.',
 'Temple architecture and courtly aesthetics shaped its iconography.',
 'Baluchari sarees are prized as artistic heirloom pieces.',
 'Fine silk weaving with jacquard support enables narrative pallu structures.',
 'Mythological scenes, arches, and floral borders are signature.',
 'Use soft wrapping and limited folding to protect motif integrity.',
 'November-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/baluchari-bishnupur/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a11',11,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa12','muga-silk-sualkuchi','Sualkuchi','Assam','Assam',26.1681,91.5714,
 'Muga Silk','Golden Assam silk known for natural sheen and resilience.',
 'Sualkuchi is a historic center for muga, eri, and pat silk weaving.',
 'Sericulture and weaving developed around Brahmaputra valley networks.',
 'Muga textiles symbolize prestige in Assamese ceremonial wear.',
 'Silk rearing, reeling, and weaving are handled through local family units.',
 'Traditional buta and border grammar emphasize regional identity.',
 'Prefer certified silk outlets for genuine muga content.',
 'October-March',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/muga-silk-sualkuchi/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a12',12,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa13','jamdani-nadia','Nadia','West Bengal','West Bengal',23.4000,88.5000,
 'Jamdani','Extra-weft muslin weaving known for airy body and floating motifs.',
 'Nadia and neighboring clusters sustain Jamdani craftsmanship.',
 'Muslin heritage and Bengal weaving schools influenced Jamdani evolution.',
 'Favored for breathable elegance and artistic weave detailing.',
 'Supplementary weft insertion forms motifs directly during weaving.',
 'Paisleys, floral sprigs, and geometric repeats are common.',
 'Avoid machine wash; preserve with gentle handling.',
 'October-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/jamdani-nadia/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a13',13,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa14','kota-doria','Kota','Rajasthan','Rajasthan',25.2138,75.8648,
 'Kota Doria','Lightweight checkered weave (khats) ideal for summer drape.',
 'Kota''s weaving clusters produce airy sarees and dress materials.',
 'Historical artisan migration and local patronage shaped the weave.',
 'Popular for daily elegance and warm-weather comfort.',
 'Cotton-silk blending and square-check loom structure define the fabric.',
 'Fine translucent checks and understated borders are key traits.',
 'Handle gently to retain texture and avoid snagging.',
 'September-March',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/kota-doria/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a14',14,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa15','venkatagiri-saree','Venkatagiri','Andhra Pradesh','Andhra Pradesh',13.9600,79.5800,
 'Venkatagiri','Fine-count handloom sarees in soft cotton and silk variants.',
 'Venkatagiri is known for refined weaving and understated elegance.',
 'Craft expanded under local courts and weaving communities.',
 'Used for ceremonial as well as lightweight formal wear.',
 'Fine yarn management and zari enhancement drive premium output.',
 'Minimalist butis and narrow zari borders are common.',
 'Select trusted cooperative stores for consistent quality.',
 'October-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/venkatagiri-saree/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a15',15,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa16','uppada-jamdani','Uppada','Andhra Pradesh','Andhra Pradesh',17.0833,82.3333,
 'Uppada Jamdani','Lightweight handloom silk with Jamdani-inspired extra-weft motifs.',
 'Uppada combines soft drape with intricate woven motif placement.',
 'Local weaving cooperatives drove scale while retaining handloom character.',
 'Favored for premium festive and wedding wear.',
 'Extra-weft insertion without heavy jacquard keeps texture light.',
 'Floral and geometric motif clusters are widely used.',
 'Inspect reverse weaving and motif finish before purchase.',
 'October-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/uppada-jamdani/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a16',16,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa17','dharmavaram-silk','Dharmavaram','Andhra Pradesh','Andhra Pradesh',14.4146,77.7195,
 'Dharmavaram Silk','Broad-border silk sarees with rich pallus and body contrast.',
 'Dharmavaram weaving emphasizes grandeur and occasion wear aesthetics.',
 'Regional weaving clusters evolved through family-loom specialization.',
 'A bridal staple in many South Indian communities.',
 'Heavier silk counts and ornate pallu work distinguish this tradition.',
 'Temple-style borders and large motif zoning are characteristic.',
 'Use breathable storage and occasional refolding.',
 'October-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/dharmavaram-silk/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a17',17,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa18','mysore-silk','Mysuru','Karnataka','Karnataka',12.2958,76.6394,
 'Mysore Silk','Smooth silk sarees with clean finish and elegant zari edges.',
 'Mysuru silk is known for purity standards and fine finishing.',
 'State-backed sericulture and weaving institutions drove standardization.',
 'Preferred for refined formal and ceremonial use.',
 'Controlled dyeing and loom finishing produce consistent texture.',
 'Solid tones with restrained zari detailing are signature.',
 'Verify hallmarking and authorized state retail channels.',
 'October-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/mysore-silk/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a18',18,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa19','kantha-shantiniketan','Shantiniketan','West Bengal','West Bengal',23.6780,87.6840,
 'Kantha Stitch Textiles','Running-stitch narrative textiles on cotton and silk bases.',
 'Shantiniketan artisan networks popularized Kantha in contemporary formats.',
 'Repurposing traditions and embroidery storytelling shaped Kantha''s identity.',
 'Used in sarees, stoles, jackets, and handcrafted home textiles.',
 'Surface hand-stitching over dyed/printed bases creates texture depth.',
 'Nature motifs, folklore scenes, and geometric stitches are common.',
 'Prefer handwash and flat drying to preserve stitch structure.',
 'October-March',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/kantha-shantiniketan/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a19',19,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa20','eri-silk-ri-bhoi','Ri Bhoi','Meghalaya','Meghalaya',25.9000,91.8000,
 'Eri Silk','Ahimsa silk known for soft warmth and matte texture.',
 'Eri silk production in Northeast India links sericulture and weaving livelihoods.',
 'Sustainable silk traditions preserved through tribal and rural communities.',
 'Valued for ethical silk narrative and all-season comfort.',
 'Spun silk process yields a wool-like drape and tactile softness.',
 'Natural shades and minimal motifing dominate many products.',
 'Check for genuine eri composition and trusted sourcing.',
 'October-March',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/eri-silk-ri-bhoi/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a20',20,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa21','kashmiri-pashmina','Srinagar','Jammu & Kashmir','Jammu & Kashmir',34.0837,74.7973,
 'Kashmiri Pashmina','Fine hand-spun and handwoven wool known for warmth and softness.',
 'Srinagar''s shawl traditions combine fiber rarity with artisanal craftsmanship.',
 'Trade and atelier systems cultivated pashmina prestige over centuries.',
 'A classic luxury textile in winter formal and heritage wardrobes.',
 'Dehairing, spinning, and weaving demand skilled specialist handling.',
 'Sozni and kani-inspired surface languages are widely recognized.',
 'Authenticate through GI-certified and reputable institutions.',
 'November-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/kashmiri-pashmina/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a21',21,TRUE),
('b8a9ef95-4894-49bf-bafb-c88831f8fa22','kutch-ajrakh','Bhuj','Gujarat','Gujarat',23.2410,69.6669,
 'Ajrakh (Kutch)','Natural-dyed block-print textile with layered resist and mordant techniques.',
 'Bhuj and Kutch craft belts sustain Ajrakh through family-led print workshops.',
 'Desert trade and artisan migration shaped Ajrakh''s visual grammar.',
 'Ajrakh is used in apparel, stoles, and design-led contemporary products.',
 'Multiple stages of washing, resist, and natural dyeing define production.',
 'Indigo-madder palettes and symmetrical geometry are signature.',
 'Expect slight artisanal variation; avoid harsh detergents.',
 'October-February',
 'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/fabric-hubs/kutch-ajrakh/cover.jpg',
 ARRAY[]::text[],
 '8f0e3a2b-7c1d-4e5f-9a0b-1c2d3e4f5a22',22,TRUE)
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    region = EXCLUDED.region,
    state = EXCLUDED.state,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    fabric_name = EXCLUDED.fabric_name,
    short_description = EXCLUDED.short_description,
    about_place_and_fabric = EXCLUDED.about_place_and_fabric,
    history = EXCLUDED.history,
    cultural_significance = EXCLUDED.cultural_significance,
    weaving_process = EXCLUDED.weaving_process,
    motifs_and_design = EXCLUDED.motifs_and_design,
    care_and_authenticity = EXCLUDED.care_and_authenticity,
    best_buying_season = EXCLUDED.best_buying_season,
    cover_image_url = EXCLUDED.cover_image_url,
    gallery_urls = EXCLUDED.gallery_urls,
    discussion_site_id = EXCLUDED.discussion_site_id,
    sort_order = EXCLUDED.sort_order,
    is_published = EXCLUDED.is_published;

INSERT INTO public.fabric_sellers (
    fabric_hub_id, seller_name, organization, seller_type,
    contact_line, website, city, is_featured, display_order
)
SELECT h.id, s.seller_name, s.organization, s.seller_type, s.contact_line, s.website, s.city, s.is_featured, s.display_order
FROM (
    VALUES
      ('kanchipuram-silk','Tamil Nadu Handloom Development Corporation','TNHDC / Co-optex network','government','State-run handloom outlets','https://www.cooptex.gov.in','Chennai',TRUE,1),
      ('kanchipuram-silk','Co-optex Kanchipuram Outlet','Tamil Nadu Handloom Weavers Co-operative','cooperative','Authorized Kanchipuram silk collections','https://www.cooptex.gov.in','Kanchipuram',TRUE,2),
      ('banarasi-silk','UP Handloom Emporium','Department of Handloom, UP','government','State emporium curated Banarasi selections',NULL,'Varanasi',TRUE,1),
      ('banarasi-silk','India Handloom Brand Partner Store','Development Commissioner (Handlooms)','verified','Check IHB-authorized Banarasi counters','https://handlooms.nic.in','Varanasi',FALSE,2),
      ('bhagalpur-tussar','Bihar Handloom Development Corp Outlet','State handloom channel','government','Bhagalpuri silk counters in state emporia',NULL,'Patna',TRUE,1),
      ('pochampally-ikat','Telangana Handloom Cooperative Showroom','TS Handloom Cooperative','cooperative','Pochampally Ikat certified collections',NULL,'Hyderabad',TRUE,1),
      ('surat-textiles','Gurjari Emporium','Gujarat State Handloom & Handicrafts Dev. Corp.','government','State outlet for curated textile products','https://gurjari.gujarat.gov.in','Ahmedabad',TRUE,1),
      ('chanderi-weave','MPTDC / Handloom Sales Counter','Madhya Pradesh State channels','government','Chanderi products in tourism + handloom outlets',NULL,'Bhopal',FALSE,1),
      ('maheshwari-weave','Rehwa Society','Maheshwari weaving collective','cooperative','Curated Maheshwari handloom collections','https://rehwasociety.org','Maheshwar',TRUE,1),
      ('patan-patola','Patan Patola Family Workshop (Verified)','Traditional weaving family unit','verified','Direct workshop purchase by appointment',NULL,'Patan',TRUE,1),
      ('paithani-yeola','Maharashtra State Handloom Outlet','State handloom sales','government','Paithani saree counters at state emporia',NULL,'Mumbai',FALSE,1),
      ('sambalpuri-ikat','Boyanika','Odisha State Cooperative Handicrafts Corp.','government','Official Sambalpuri and Ikat collections','https://www.boyanika.com','Bhubaneswar',TRUE,1),
      ('baluchari-bishnupur','Manjusha / State Emporium','West Bengal Handloom channels','government','Baluchari curated selections',NULL,'Kolkata',FALSE,1),
      ('muga-silk-sualkuchi','Assam Apex Weavers & Artisans Cooperative','State cooperative ecosystem','cooperative','Muga silk certified products',NULL,'Guwahati',TRUE,1),
      ('jamdani-nadia','Biswa Bangla Store','West Bengal govt-backed retail','government','Jamdani listings in official outlets','https://www.biswabangla.in','Kolkata',FALSE,1),
      ('kota-doria','Kota Doria Development Society','Cluster-level cooperative support','cooperative','Authentic Kota Doria looms',NULL,'Kota',TRUE,1),
      ('venkatagiri-saree','AP Handloom Weavers Cooperative Outlet','Andhra Pradesh handloom network','cooperative','Venkatagiri handloom sarees',NULL,'Nellore',FALSE,1),
      ('uppada-jamdani','Uppada Cooperative Sales Center','Local handloom cooperative','cooperative','Uppada Jamdani weaves',NULL,'Kakinada',TRUE,1),
      ('dharmavaram-silk','AP State Handloom Emporium','State-run textile retail','government','Dharmavaram silk collections',NULL,'Anantapur',FALSE,1),
      ('mysore-silk','KSIC Mysore Silk Showroom','Karnataka Silk Industries Corporation','government','Certified Mysore silk sarees','https://ksicsilk.com','Mysuru',TRUE,1),
      ('kantha-shantiniketan','Bangla Craft Cluster Outlet','Government-supported artisan cluster','verified','Kantha products from artisan groups',NULL,'Bolpur',FALSE,1),
      ('eri-silk-ri-bhoi','NERAMAC Partner Outlet','Northeast agri-marketing corporation channel','government','Eri and regional silk products','https://neramac.com','Shillong',FALSE,1),
      ('kashmiri-pashmina','J&K Handloom Department Showroom','Government handloom department','government','Certified Kashmiri pashmina channels',NULL,'Srinagar',TRUE,1),
      ('kutch-ajrakh','Kutch Craft Cooperative Counter','Cluster-supported verified retail','cooperative','Ajrakh block-printed textiles',NULL,'Bhuj',TRUE,1)
) AS s(slug, seller_name, organization, seller_type, contact_line, website, city, is_featured, display_order)
JOIN public.fabric_hubs h ON h.slug = s.slug
ON CONFLICT DO NOTHING;

