-- Seed 20 prominent non-fabric Indian craft hubs with curated details.
-- Image URL convention:
-- craft-hubs/{slug}/cover.jpg and craft-hubs/{slug}/gallery/1.jpg

INSERT INTO public.craft_hubs (
    id, slug, name, region, state, latitude, longitude, craft_name,
    short_description, about_place_and_craft, history, cultural_significance,
    making_process, materials, motifs_and_style, care_and_authenticity,
    best_buying_season, cover_image_url, gallery_urls, discussion_site_id,
    sort_order, is_published
) VALUES
('7b8aa801-a1f1-4a5f-a001-000000000001','channapatna-toys','Channapatna','Karnataka','Karnataka',12.6500,77.2100,'Channapatna Wooden Toys','Lacquered wooden toys known for vibrant non-toxic finishes.','Channapatna is a major handcrafted toy cluster using turned wood and natural color techniques for toys and decor products.','The craft expanded through artisan lineages and institutional craft support in Karnataka.','It is a heritage toy tradition representing safe and sustainable child-friendly craft practices.','Wood is lathe-turned, shaped, coated with natural pigments, and polished by hand.','Wrightia tinctoria wood, natural colors, lacquer.','Rounded forms, bold stripes, child-safe toy silhouettes.','Buy from certified clusters and avoid synthetic over-coated copies.','October-February','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/channapatna-toys/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/channapatna-toys/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000001',1,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000002','kondapalli-toys','Kondapalli','Andhra Pradesh','Andhra Pradesh',16.6200,80.5400,'Kondapalli Toys','Hand-carved figurines made from local softwood and painted folk scenes.','Kondapalli artisans produce storytelling figurines, festive dolls, and village tableau pieces from lightweight wood.','The craft has survived through dedicated artisan communities and local patronage networks.','Kondapalli toys preserve visual narratives of agrarian life and mythic storytelling.','Wood carving, joining, smoothing, hand-painting, and detailing are done in sequence.','Tella poniki wood, natural and acrylic colors, adhesive compounds.','Village scenes, dancers, deities, processional motifs.','Check hand-finishing quality and source from registered artisan groups.','September-February','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/kondapalli-toys/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/kondapalli-toys/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000002',2,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000003','bidriware','Bidar','Karnataka','Karnataka',17.9100,77.5200,'Bidriware','Blackened metal inlay craft with silver arabesque and geometric motifs.','Bidriware combines alloy casting with fine silver inlay on an oxidized black surface to produce premium decor and utility pieces.','The craft grew under Deccan court patronage and specialist metalworking guilds.','Bidri objects are considered collectible heritage craft products and ceremonial gifts.','Casting, engraving, silver-wire inlay, blackening, polishing.','Zinc-copper alloy, silver wire/sheet, polishing compounds.','Floral creepers, geometric grids, Persian-inspired calligraphic flow.','Prefer hallmarked trusted sellers and inspect inlay depth and finish consistency.','October-March','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/bidriware/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/bidriware/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000003',3,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000004','jaipur-blue-pottery','Jaipur','Rajasthan','Rajasthan',26.9124,75.7873,'Jaipur Blue Pottery','Quartz-based glazed pottery with cobalt blue floral aesthetics.','Jaipur blue pottery is made with a low-clay body and glazed decorative finish used in tiles, tableware, and decorative pieces.','The style blended Persian influence with local Jaipur workshop traditions.','It is a flagship urban craft identity of Rajasthan and tourism-linked artisan economy.','Body preparation, moulding, hand-painting, glazing, kiln firing.','Quartz powder, glass powder, natural gums, mineral pigments.','Cobalt blue florals, vines, birds, and repetitive tile patterns.','Avoid low-fired imitation pieces and buy through recognized craft centers.','October-February','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/jaipur-blue-pottery/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/jaipur-blue-pottery/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000004',4,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000005','pattachitra-raghurajpur','Raghurajpur','Odisha','Odisha',19.9600,85.8300,'Pattachitra Painting','Mythological narrative painting on cloth and palm-leaf formats.','Raghurajpur artists create devotional and storytelling artworks with natural pigments and meticulous line discipline.','The craft is linked to temple traditions and inherited painter lineages in Odisha.','Pattachitra carries ritual narratives and visual pedagogy of epic literature.','Surface preparation, sketching, natural pigment layering, outlining, varnishing.','Cloth, tamarind seed paste, chalk base, natural pigments.','Epic episodes, Jagannath iconography, ornamental borders.','Prefer artists with provenance and avoid machine-printed reproductions sold as originals.','November-March','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/pattachitra-raghurajpur/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/pattachitra-raghurajpur/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000005',5,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000006','dhokra-bastar','Kondagaon','Chhattisgarh','Chhattisgarh',19.6000,81.6700,'Dhokra Metal Casting','Lost-wax tribal metal craft with earthy sculptural character.','Bastar Dhokra artisans produce figurative and ritual objects through the cire perdue process and hand-finished casting.','The tradition is rooted in indigenous metalcraft and ritual economies across central India.','Dhokra embodies tribal expression and symbolic material culture.','Wax model creation, clay moulding, molten metal pour, break mould, finish surface.','Beeswax, clay, brass scraps, charcoal-fired furnaces.','Human figures, animals, ritual scenes, textured rustic surfaces.','Each piece is unique; validate authenticity from cooperative channels.','October-February','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/dhokra-bastar/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/dhokra-bastar/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000006',6,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000007','saharanpur-wood-carving','Saharanpur','Uttar Pradesh','Uttar Pradesh',29.9700,77.5500,'Saharanpur Wood Carving','Intricate carved wood decor and furniture craft cluster.','Saharanpur specializes in carved panels, furniture, and utility decor based on traditional hand tools and workshop discipline.','The craft evolved through Mughal-period aesthetics and urban workshop production networks.','A major employment craft with strong domestic and export market presence.','Wood seasoning, marking, hand-chiseling, carving, finishing, polishing.','Sheesham and mango wood, carving tools, natural/chemical polish.','Jali work, floral vines, arabesque, geometric relief panels.','Check wood seasoning and joinery quality before purchase.','October-March','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/saharanpur-wood-carving/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/saharanpur-wood-carving/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000007',7,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000008','moradabad-brassware','Moradabad','Uttar Pradesh','Uttar Pradesh',28.8386,78.7733,'Moradabad Brassware','Hammered, cast, and etched brass utility and decor products.','Moradabad is a large brass cluster producing artisanal decor, tableware, and giftware with varied finishing styles.','The city became prominent through long-standing metal trading and workshop specialization.','Brass craft supports both heritage expression and contemporary design exports.','Casting/sheet work, turning, engraving, polishing, coating, finishing.','Brass sheets, cast alloy, etching compounds, polishing media.','Embossed textures, floral etching, polished and antique finishes.','Check coating durability and corrosion resistance in utility pieces.','September-March','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/moradabad-brassware/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/moradabad-brassware/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000008',8,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000009','kashmir-paper-mache','Srinagar','Jammu & Kashmir','Jammu & Kashmir',34.0837,74.7973,'Kashmir Paper Mache','Hand-moulded and painted decorative papier-mache objects.','Artisans produce boxes, ornaments, and decor with layered paper pulp and fine floral hand-painting.','The craft reflects centuries-old Kashmir atelier traditions and Persian influence.','Paper mache is both a livelihood craft and an emblem of Kashmiri design language.','Pulp preparation, moulding, drying, smoothing, painting, lacquering.','Waste paper pulp, adhesives, mineral pigments, lacquer.','Chinar leaves, floral vines, birds, and miniature scene painting.','Avoid printed substitutes and verify hand-painted detailing.','May-October','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/kashmir-paper-mache/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/kashmir-paper-mache/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000009',9,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000010','kashmir-walnut-carving','Srinagar','Jammu & Kashmir','Jammu & Kashmir',34.0900,74.7900,'Walnut Wood Carving','Detailed walnut wood carving for furniture and decor.','Kashmir walnut carving transforms seasoned walnut wood into premium carved utility and heirloom decor.','Royal patronage and family workshop transmission sustained the carving tradition.','The craft is a marker of Kashmiri artisanal luxury and home aesthetics.','Wood selection, seasoning, sketch transfer, carving, burnishing, finish.','Walnut wood, chisels, hand files, polishing oils.','Deep relief carving, paisley, lotus, lattice patterns.','Inspect grain continuity and depth consistency in carved surfaces.','April-October','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/kashmir-walnut-carving/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/kashmir-walnut-carving/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000010',10,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000011','kutch-rogan-art','Nirona','Gujarat','Gujarat',23.4500,69.5200,'Rogan Art','Castor-oil-based paint drawing on cloth using stylus-like metal tools.','Rogan is a rare freehand painted craft where paste-like pigment is drawn into intricate motifs without direct brush contact.','The tradition survived in select artisan families in Kutch.','Rogan motifs became a symbol of endangered heritage art revival.','Rogan paste preparation, hand drawing, mirror transfer, heat setting.','Castor oil, natural pigments, treated cloth base.','Tree of life and symmetrical floral compositions are iconic.','Purchase from practicing lineage artists to ensure authenticity.','November-February','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/kutch-rogan-art/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/kutch-rogan-art/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000011',11,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000012','madhubani-painting','Madhubani','Bihar','Bihar',26.3500,86.0700,'Madhubani Painting','Folk painting with dense patterning and mythological subjects.','Madhubani painters create vibrant line-heavy compositions on paper, wall, and utility surfaces inspired by regional storytelling.','The art transitioned from wall traditions to portable market formats over the last century.','A major women-led folk art economy and cultural identity of Mithila.','Sketching, double-line drawing, color fill, decorative infill patterning.','Natural and synthetic pigments, handmade paper, bamboo nibs.','Mythological figures, flora-fauna, geometric infill backgrounds.','Prefer signed works from registered artist collectives.','October-March','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/madhubani-painting/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/madhubani-painting/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000012',12,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000013','cheriyal-scrolls','Cheriyal','Telangana','Telangana',17.3500,78.8600,'Cheriyal Scroll Painting','Narrative scroll painting tradition depicting epics and folk histories.','Cheriyal artists make story-scrolls and masks that illustrate regional oral traditions and religious narratives.','The craft served as a visual storytelling medium for itinerant performers.','Cheriyal is vital to preserving oral folklore in visual form.','Cloth treatment, composition planning, figurative painting, line reinforcement.','Treated cloth, natural pigments, gum binder, handmade brushes.','Bold flat colors, expressive faces, sequential narrative panels.','Buy from artisans and craft museums preserving traditional formats.','November-February','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/cheriyal-scrolls/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/cheriyal-scrolls/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000013',13,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000014','etikoppaka-toys','Etikoppaka','Andhra Pradesh','Andhra Pradesh',17.5100,82.9800,'Etikoppaka Lac Toys','Lac-turned wooden toys and utility items with natural dyes.','Etikoppaka craft uses turned wood and natural lac colors for toys, kitchenware, and decor objects.','The craft developed around local wood and hereditary artisan practices.','It reflects eco-conscious craft making and educational toy culture.','Wood turning, shaping, lac-color application, polishing.','Ankudu wood, natural lac, vegetable pigments.','Smooth rounded geometry and clean color bands.','Choose non-toxic certified products from artisan cooperatives.','October-February','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/etikoppaka-toys/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/etikoppaka-toys/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000014',14,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000015','thanjavur-painting','Thanjavur','Tamil Nadu','Tamil Nadu',10.7867,79.1378,'Thanjavur Painting','Relief devotional painting with gold foil accents and jewel-like detailing.','Thanjavur painting blends iconography, relief gesso, and gold embellishment for temple-inspired artworks.','The style matured in temple-town atelier environments under regional court influence.','It remains a major devotional art purchase in South India.','Board preparation, relief work, foil application, pigment painting, varnishing.','Wooden board, chalk paste, gold foil, stones, pigments.','Centered deity compositions with ornamental arches and rich backgrounds.','Verify foil quality and artist provenance before high-value purchase.','October-March','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/thanjavur-painting/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/thanjavur-painting/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000015',15,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000016','stone-carving-mahabalipuram','Mahabalipuram','Tamil Nadu','Tamil Nadu',12.6208,80.1945,'Stone Carving','Traditional sculptural stone carving inspired by temple iconography.','Mahabalipuram workshops produce deity sculptures, relief panels, and architectural carvings in granite and soapstone.','The craft continues a long sculptural lineage linked to temple architecture.','It sustains ritual art skills and heritage conservation expertise.','Block selection, rough shaping, chiseling, detailing, polishing.','Granite, soapstone, chisels, pneumatic and hand tools.','Temple motifs, deities, yali, ornamental columns.','Check stone quality and artisan credentials for structural pieces.','November-February','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/stone-carving-mahabalipuram/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/stone-carving-mahabalipuram/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000016',16,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000017','terracotta-bishnupur','Bishnupur','West Bengal','West Bengal',23.0742,87.3199,'Terracotta Craft','Hand-moulded terracotta horses, panels, and ritual decor forms.','Bishnupur terracotta craft includes iconic horse figurines and temple-inspired relief artwork.','The tradition evolved with local clay availability and temple-town craft demand.','Terracotta objects are widely used in folk decor and ceremonial gifting.','Clay preparation, hand shaping, detailing, sun-drying, kiln firing.','Alluvial clay, mineral slips, simple natural glazes.','Bankura horse forms, folk figurines, geometric relief.','Inspect firing quality and crack resistance in larger pieces.','November-February','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/terracotta-bishnupur/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/terracotta-bishnupur/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000017',17,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000018','dokra-bengal','Bikna','West Bengal','West Bengal',23.3500,87.2000,'Dokra Casting (Bengal)','Lost-wax metal craft with folk and ritual object themes.','Bengal Dokra craft produces figurative brass objects with textured artisanal finish and symbolic motifs.','The craft persists through hereditary artisan pockets in Bengal.','Dokra pieces are sought after as collectible tribal-inspired craft objects.','Wax model making, clay moulding, metal casting, break and finish.','Wax, clay, brass scrap, hand tools.','Folk deities, musicians, animals, ritual scenes.','Each cast is unique; buy from artisan cooperatives and verified craft stores.','October-February','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/dokra-bengal/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/dokra-bengal/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000018',18,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000019','banaras-gulabi-meenakari','Varanasi','Uttar Pradesh','Uttar Pradesh',25.3176,82.9739,'Gulabi Meenakari','Pink enamel jewelry and decorative metal craft from Varanasi.','Gulabi meenakari artisans apply enamel work on silver and copper surfaces with refined miniature precision.','The tradition developed in courtly craft ecosystems and goldsmith lanes.','It represents high-value luxury craft and ceremonial adornment culture.','Surface cleaning, engraving, enamel filling, firing, polishing.','Silver/copper base, enamel powders, heating tools.','Floral pink enamel, delicate arabesque and miniature motifs.','Buy hallmark-backed pieces and ask for process transparency.','October-March','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/banaras-gulabi-meenakari/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/banaras-gulabi-meenakari/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000019',19,TRUE),
('7b8aa801-a1f1-4a5f-a001-000000000020','naga-bamboo-craft','Kohima','Nagaland','Nagaland',25.6701,94.1077,'Bamboo and Cane Craft','Handwoven and assembled bamboo-cane utility and lifestyle craft.','Naga craft clusters produce baskets, home utility objects, and decor from local bamboo and cane resources.','The practice is embedded in community craftsmanship and ecological material culture.','It supports sustainable rural livelihoods and indigenous design traditions.','Splitting, weaving, shaping, binding, smoke treatment, finishing.','Bamboo, cane, natural fibers, local dyes.','Basket weave geometry, utility forms, tribal design accents.','Check for treatment quality and secure weaving in utility products.','September-February','https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/naga-bamboo-craft/cover.jpg',ARRAY['https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/craft-hubs/naga-bamboo-craft/gallery/1.jpg'],'7b8aa801-a1f1-4a5f-b001-000000000020',20,TRUE)
ON CONFLICT (id) DO UPDATE SET
    slug = EXCLUDED.slug,
    name = EXCLUDED.name,
    region = EXCLUDED.region,
    state = EXCLUDED.state,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    craft_name = EXCLUDED.craft_name,
    short_description = EXCLUDED.short_description,
    about_place_and_craft = EXCLUDED.about_place_and_craft,
    history = EXCLUDED.history,
    cultural_significance = EXCLUDED.cultural_significance,
    making_process = EXCLUDED.making_process,
    materials = EXCLUDED.materials,
    motifs_and_style = EXCLUDED.motifs_and_style,
    care_and_authenticity = EXCLUDED.care_and_authenticity,
    best_buying_season = EXCLUDED.best_buying_season,
    cover_image_url = EXCLUDED.cover_image_url,
    gallery_urls = EXCLUDED.gallery_urls,
    discussion_site_id = EXCLUDED.discussion_site_id,
    sort_order = EXCLUDED.sort_order,
    is_published = EXCLUDED.is_published;

INSERT INTO public.craft_sellers (
    craft_hub_id, seller_name, organization, seller_type, contact_line,
    website, city, is_featured, display_order
)
SELECT
    ch.id,
    s.seller_name,
    s.organization,
    s.seller_type,
    s.contact_line,
    s.website,
    s.city,
    s.is_featured,
    s.display_order
FROM (
    VALUES
    ('channapatna-toys','Karnataka State Emporium','Cauvery Karnataka Arts & Crafts','government','Official craft outlet and helpline','https://cauveryhandicrafts.karnataka.gov.in','Bengaluru',TRUE,1),
    ('channapatna-toys','Toy Cluster Cooperative','Channapatna Artisan Cooperative','cooperative','Cluster office support desk','https://karnatakaone.gov.in','Channapatna',FALSE,2),
    ('kondapalli-toys','AP Lepakshi','Andhra Pradesh Handicrafts Development','government','State handicrafts support center','https://www.aplepakshi.com','Vijayawada',TRUE,1),
    ('kondapalli-toys','Kondapalli Artisan Society','Kondapalli Crafts Cooperative','cooperative','Registered artisan cooperative desk','https://www.apcoonline.in','Kondapalli',FALSE,2),
    ('bidriware','Karnataka Crafts Sales Cell','State Handicrafts Marketing','government','Official Bidri sales facilitation','https://karnataka.gov.in','Bengaluru',TRUE,1),
    ('bidriware','Bidri Artisan Guild','Bidar Inlay Cooperative','cooperative','Guild office support','https://www.craftscouncilofindia.org','Bidar',FALSE,2),
    ('jaipur-blue-pottery','Rajasthan Craft Hub','Rajasthan Small Industries Corp','government','Blue pottery support desk','https://www.rsic.rajasthan.gov.in','Jaipur',TRUE,1),
    ('jaipur-blue-pottery','Jaipur Blue Pottery Center','Certified Artisan Collective','verified','Craft studio support','https://www.rajasthanstudio.com','Jaipur',FALSE,2),
    ('pattachitra-raghurajpur','Odisha State Emporium','Boyanika Handicrafts Channel','government','State craft retail facilitation','https://www.boyanika.com','Bhubaneswar',TRUE,1),
    ('pattachitra-raghurajpur','Raghurajpur Artist Collective','Village Artisan Cooperative','cooperative','Artist village info desk','https://odishatourism.gov.in','Raghurajpur',FALSE,2),
    ('dhokra-bastar','Chhattisgarh Craft Board','State Tribal Craft Facilitation','government','Tribal craft support helpline','https://www.tribal.cg.gov.in','Raipur',TRUE,1),
    ('dhokra-bastar','Bastar Dhokra Collective','Artisan Cooperative Society','cooperative','Workshop cluster office','https://www.tribesindia.com','Kondagaon',FALSE,2),
    ('saharanpur-wood-carving','UP Handicrafts Desk','UP Export & Crafts Facilitation','government','Official cluster guidance','https://www.upgov.in','Saharanpur',TRUE,1),
    ('moradabad-brassware','Moradabad Metal Craft Cell','State-supported brass cluster office','government','Quality and market support line','https://www.epch.in','Moradabad',TRUE,1),
    ('kashmir-paper-mache','J&K Arts Cell','J&K Handicrafts Department','government','Certified artisan registry support','https://www.jkhandicrafts.com','Srinagar',TRUE,1),
    ('kashmir-walnut-carving','Kashmir Walnut Collective','Registered Artisan Cooperative','cooperative','Workshop and purchase support','https://www.jktdc.co.in','Srinagar',FALSE,2),
    ('kutch-rogan-art','Gujarat Crafts Council','State Craft Promotion Desk','government','Rogan craft support desk','https://www.gujarattourism.com','Bhuj',TRUE,1),
    ('madhubani-painting','Mithila Art Federation','Madhubani Artist Network','verified','Artist certification support','https://www.biharcrafts.in','Madhubani',TRUE,1),
    ('cheriyal-scrolls','Telangana Handicrafts','State Crafts Development','government','Cheriyal craft support','https://www.telanganatourism.gov.in','Hyderabad',TRUE,1),
    ('etikoppaka-toys','Etikoppaka Cooperative','Lac Toy Artisan Cooperative','cooperative','Village cluster office','https://www.apcoonline.in','Etikoppaka',FALSE,2),
    ('thanjavur-painting','Tamil Nadu Poompuhar','Tamil Nadu Handicrafts Development Corp','government','Official handicrafts retail','https://www.poompuhar.org','Chennai',TRUE,1),
    ('stone-carving-mahabalipuram','Mahabalipuram Sculptors Center','Sculptors Welfare Society','cooperative','Sculpture cluster support','https://www.tamilnadutourism.tn.gov.in','Mahabalipuram',FALSE,2),
    ('terracotta-bishnupur','Bengal Craft Support Cell','State Terracotta Promotion','government','Craft facilitation desk','https://www.wbtourism.gov.in','Bishnupur',TRUE,1),
    ('dokra-bengal','Dokra Welfare Cooperative','Bengal Dokra Artisans','cooperative','Cluster marketing support','https://www.biswabangla.in','Bikna',FALSE,2),
    ('banaras-gulabi-meenakari','UP Heritage Craft Desk','State Heritage Craft Channel','government','Certified meenakari desk','https://www.up.gov.in','Varanasi',TRUE,1),
    ('naga-bamboo-craft','Nagaland Bamboo Mission','State Bamboo and Cane Cell','government','Cluster training and market linkage','https://www.nagaland.gov.in','Kohima',TRUE,1)
) AS s(slug, seller_name, organization, seller_type, contact_line, website, city, is_featured, display_order)
JOIN public.craft_hubs ch ON ch.slug = s.slug;

