-- Seed state-level pins for Indian classical artforms and classical dances.
-- One hub per state/UT per category. Items are mapped to state hubs.

WITH hub_seed(category, state_code, state_name, latitude, longitude, pin_hide_zoom_max, sort_order) AS (
  VALUES
    ('classical_art','IN-AP','Andhra Pradesh',15.9129,79.7400,7.6,1),
    ('classical_art','IN-AR','Arunachal Pradesh',28.2180,94.7278,8.6,2),
    ('classical_art','IN-AS','Assam',26.2006,92.9376,8.3,3),
    ('classical_art','IN-BR','Bihar',25.0961,85.3131,7.9,4),
    ('classical_art','IN-CT','Chhattisgarh',21.2787,81.8661,7.7,5),
    ('classical_art','IN-GA','Goa',15.2993,74.1240,8.9,6),
    ('classical_art','IN-GJ','Gujarat',22.2587,71.1924,7.5,7),
    ('classical_art','IN-HR','Haryana',29.0588,76.0856,8.1,8),
    ('classical_art','IN-HP','Himachal Pradesh',31.1048,77.1734,8.5,9),
    ('classical_art','IN-JH','Jharkhand',23.6102,85.2799,8.0,10),
    ('classical_art','IN-KA','Karnataka',15.3173,75.7139,7.4,11),
    ('classical_art','IN-KL','Kerala',10.8505,76.2711,8.0,12),
    ('classical_art','IN-MP','Madhya Pradesh',22.9734,78.6569,7.3,13),
    ('classical_art','IN-MH','Maharashtra',19.7515,75.7139,7.2,14),
    ('classical_art','IN-MN','Manipur',24.6637,93.9063,8.7,15),
    ('classical_art','IN-ML','Meghalaya',25.4670,91.3662,8.7,16),
    ('classical_art','IN-MZ','Mizoram',23.1645,92.9376,8.8,17),
    ('classical_art','IN-NL','Nagaland',26.1584,94.5624,8.7,18),
    ('classical_art','IN-OR','Odisha',20.9517,85.0985,7.8,19),
    ('classical_art','IN-PB','Punjab',31.1471,75.3412,8.1,20),
    ('classical_art','IN-RJ','Rajasthan',27.0238,74.2179,7.2,21),
    ('classical_art','IN-SK','Sikkim',27.5330,88.5122,8.8,22),
    ('classical_art','IN-TN','Tamil Nadu',11.1271,78.6569,7.4,23),
    ('classical_art','IN-TS','Telangana',18.1124,79.0193,7.8,24),
    ('classical_art','IN-TR','Tripura',23.9408,91.9882,8.7,25),
    ('classical_art','IN-UP','Uttar Pradesh',26.8467,80.9462,7.1,26),
    ('classical_art','IN-UK','Uttarakhand',30.0668,79.0193,8.4,27),
    ('classical_art','IN-WB','West Bengal',22.9868,87.8550,7.8,28),
    ('classical_art','IN-AN','Andaman and Nicobar Islands',11.7401,92.6586,8.9,29),
    ('classical_art','IN-CH','Chandigarh',30.7333,76.7794,9.0,30),
    ('classical_art','IN-DN','Dadra and Nagar Haveli and Daman and Diu',20.3974,72.8328,8.9,31),
    ('classical_art','IN-DL','Delhi',28.7041,77.1025,8.9,32),
    ('classical_art','IN-JK','Jammu and Kashmir',33.7782,76.5762,8.5,33),
    ('classical_art','IN-LA','Ladakh',34.1526,77.5770,8.9,34),
    ('classical_art','IN-LD','Lakshadweep',10.5667,72.6417,9.0,35),
    ('classical_art','IN-PY','Puducherry',11.9416,79.8083,8.9,36),
    ('classical_dance','IN-AP','Andhra Pradesh',15.9129,79.7400,7.6,1),
    ('classical_dance','IN-AR','Arunachal Pradesh',28.2180,94.7278,8.6,2),
    ('classical_dance','IN-AS','Assam',26.2006,92.9376,8.3,3),
    ('classical_dance','IN-BR','Bihar',25.0961,85.3131,7.9,4),
    ('classical_dance','IN-CT','Chhattisgarh',21.2787,81.8661,7.7,5),
    ('classical_dance','IN-GA','Goa',15.2993,74.1240,8.9,6),
    ('classical_dance','IN-GJ','Gujarat',22.2587,71.1924,7.5,7),
    ('classical_dance','IN-HR','Haryana',29.0588,76.0856,8.1,8),
    ('classical_dance','IN-HP','Himachal Pradesh',31.1048,77.1734,8.5,9),
    ('classical_dance','IN-JH','Jharkhand',23.6102,85.2799,8.0,10),
    ('classical_dance','IN-KA','Karnataka',15.3173,75.7139,7.4,11),
    ('classical_dance','IN-KL','Kerala',10.8505,76.2711,8.0,12),
    ('classical_dance','IN-MP','Madhya Pradesh',22.9734,78.6569,7.3,13),
    ('classical_dance','IN-MH','Maharashtra',19.7515,75.7139,7.2,14),
    ('classical_dance','IN-MN','Manipur',24.6637,93.9063,8.7,15),
    ('classical_dance','IN-ML','Meghalaya',25.4670,91.3662,8.7,16),
    ('classical_dance','IN-MZ','Mizoram',23.1645,92.9376,8.8,17),
    ('classical_dance','IN-NL','Nagaland',26.1584,94.5624,8.7,18),
    ('classical_dance','IN-OR','Odisha',20.9517,85.0985,7.8,19),
    ('classical_dance','IN-PB','Punjab',31.1471,75.3412,8.1,20),
    ('classical_dance','IN-RJ','Rajasthan',27.0238,74.2179,7.2,21),
    ('classical_dance','IN-SK','Sikkim',27.5330,88.5122,8.8,22),
    ('classical_dance','IN-TN','Tamil Nadu',11.1271,78.6569,7.4,23),
    ('classical_dance','IN-TS','Telangana',18.1124,79.0193,7.8,24),
    ('classical_dance','IN-TR','Tripura',23.9408,91.9882,8.7,25),
    ('classical_dance','IN-UP','Uttar Pradesh',26.8467,80.9462,7.1,26),
    ('classical_dance','IN-UK','Uttarakhand',30.0668,79.0193,8.4,27),
    ('classical_dance','IN-WB','West Bengal',22.9868,87.8550,7.8,28),
    ('classical_dance','IN-AN','Andaman and Nicobar Islands',11.7401,92.6586,8.9,29),
    ('classical_dance','IN-CH','Chandigarh',30.7333,76.7794,9.0,30),
    ('classical_dance','IN-DN','Dadra and Nagar Haveli and Daman and Diu',20.3974,72.8328,8.9,31),
    ('classical_dance','IN-DL','Delhi',28.7041,77.1025,8.9,32),
    ('classical_dance','IN-JK','Jammu and Kashmir',33.7782,76.5762,8.5,33),
    ('classical_dance','IN-LA','Ladakh',34.1526,77.5770,8.9,34),
    ('classical_dance','IN-LD','Lakshadweep',10.5667,72.6417,9.0,35),
    ('classical_dance','IN-PY','Puducherry',11.9416,79.8083,8.9,36)
)
INSERT INTO public.cultural_state_hubs (
  category, slug, state_code, state_name, latitude, longitude, pin_hide_zoom_max, sort_order, is_published
)
SELECT
  s.category,
  lower(concat(s.category, '-', replace(s.state_code, 'IN-', ''))),
  s.state_code,
  s.state_name,
  s.latitude,
  s.longitude,
  s.pin_hide_zoom_max,
  s.sort_order,
  TRUE
FROM hub_seed s
ON CONFLICT (category, state_code) DO UPDATE SET
  slug = EXCLUDED.slug,
  state_name = EXCLUDED.state_name,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  pin_hide_zoom_max = EXCLUDED.pin_hide_zoom_max,
  sort_order = EXCLUDED.sort_order,
  is_published = EXCLUDED.is_published;

WITH item_seed(category, state_code, item_name, short_description, about_state_tradition, history, cultural_significance, practice_and_pedagogy, performance_context, notable_exponents, sort_order) AS (
  VALUES
    ('classical_art','IN-AP','Kalamkari Visual Tradition','Narrative hand-painted and block-printed classical textile art tradition.','Andhra Pradesh preserves scriptural and court-linked Kalamkari storytelling styles.','Temple and court ateliers shaped this visual grammar across centuries.','The artform encodes epic narratives and sacred iconography for public memory.','Training focuses on natural dyes, line discipline, and scene composition.','Displayed in heritage galleries, ritual spaces, and curated design showcases.','Machilipatnam and Srikalahasti lineage artists.',1),
    ('classical_art','IN-AR','Monpa Thangka Tradition','Sacred scroll painting with Buddhist iconographic discipline.','Arunachal monastic circuits preserve high-altitude thangka iconography.','Himalayan transmission brought codified icon and color systems.','The form serves meditation, pedagogy, and sacred visual continuity.','Apprenticeship emphasizes geometry, symbolism, and pigment layering.','Seen in monasteries, ritual halls, and heritage exhibitions.','Tawang monastic artist lineages.',1),
    ('classical_art','IN-AS','Majuli Mask Craft Theatre Art','Ritual mask-making linked to Sattriya theatre expression.','Assam Vaishnavite monasteries sustain mask arts tied to performance tradition.','Satra institutions developed codified theatrical visual language.','Masks carry devotional narratives and pedagogical symbolism.','Practice includes clay layering, bamboo structure, and painted finishing.','Used in Bhaona productions and monastery festivals.','Majuli satra artisan families.',1),
    ('classical_art','IN-BR','Madhubani Painting','Mythological and ceremonial painting tradition with dense motif grammar.','Bihar''s Mithila region keeps a living visual language across ritual calendars.','From wall traditions, the form moved into paper and museum circuits.','The artform documents social memory, devotion, and ecological symbolism.','Training centers on line rhythm, pattern fill, and color symbolism.','Featured in cultural fairs, galleries, and educational circuits.','Mithila women-led artist collectives.',1),
    ('classical_art','IN-CT','Bastar Dhokra Sculpture','Lost-wax metal sculpture tradition with ritual and folk iconography.','Chhattisgarh tribal belts sustain a long cire-perdue sculptural heritage.','Metal casting lineages evolved around ritual economy and local markets.','The form embodies indigenous philosophy, memory, and material mastery.','Pedagogy includes wax modelling, mould prep, and brass casting.','Presented in craft museums, heritage markets, and cultural biennales.','Bastar dokra artisan groups.',1),
    ('classical_art','IN-GA','Mando Music-Theatre Visual Art','Classical Goan stage aesthetics blending music, costume, and visual storytelling.','Goa developed a court and church-influenced performance visuality.','Colonial-era music theatre shaped costume and set traditions.','It reflects Goa''s plural cultural expression and refined stage idiom.','Training integrates repertoire, attire grammar, and dramatic staging.','Performed in seasonal cultural festivals and state showcases.','Traditional mando ensembles.',1),
    ('classical_art','IN-GJ','Pithora Ritual Painting','Ceremonial wall-painting tradition tied to devotional and social rites.','Gujarat''s tribal communities sustain codified ritual icon painting.','The form evolved in household and shrine ceremonial contexts.','It encodes cosmology, ancestry, and community identity.','Learning follows ritual protocol, pigment prep, and symbol sequencing.','Displayed in ritual events and curated folk-art platforms.','Rathwa and Bhilala painters.',1),
    ('classical_art','IN-HR','Phulkari Heritage Embroidery Art','Classical embroidery art with geometric and floral stitch logic.','Haryana keeps needlework traditions linked to festive and lifecycle contexts.','Community guild practice transmitted motifs across generations.','The form carries domestic memory and ceremonial aesthetics.','Training emphasizes stitch density, composition, and color rhythm.','Exhibited in textiles museums and state handcraft pavilions.','Regional embroidery cooperatives.',1),
    ('classical_art','IN-HP','Kangra Miniature Painting','Pahari miniature painting tradition known for lyrical narrative panels.','Himachal ateliers retain refined miniature canons and ragamala iconography.','Court patronage made Kangra painting a classical visual school.','Its poetic visual language shaped North Indian art pedagogy.','Apprenticeship focuses on brush control, palette, and layering.','Shown in heritage galleries and state art academies.','Kangra atelier practitioners.',1),
    ('classical_art','IN-JH','Sohrai-Khovar Wall Art','Ceremonial mural tradition with ecological and fertility symbolism.','Jharkhand village communities sustain seasonal wall-art traditions.','The form grew from ritual house-decoration practices.','It preserves oral-symbolic memory around seasons and land.','Practice includes natural pigment prep and gestural mural composition.','Visible in village festivals and curated folk-art residencies.','Hazaribagh women artists.',1),
    ('classical_art','IN-KA','Mysore Painting','Classical painting school with devotional icon precision and luminous finish.','Karnataka maintains Mysore atelier methods and temple-linked themes.','Court and temple patronage structured this canonical art school.','It remains central to South Indian devotional visual culture.','Training covers gesso work, line discipline, and iconography.','Displayed in cultural museums and classical art exhibitions.','Mysore traditional ateliers.',1),
    ('classical_art','IN-KL','Kathakali Chutti Visual Design','Classical facial design and costume art tied to dramatic dance theatre.','Kerala preserves codified makeup, costume, and visual semiotics for stage.','Temple and royal circuits formalized this visual performance grammar.','It transforms theatre into symbolic visual language.','Pedagogy includes costume prep, color codes, and character mapping.','Practiced in kalari schools and performance venues.','Kerala kalari masters.',1),
    ('classical_art','IN-MP','Gond Narrative Art','Classical indigenous narrative art with patterned ecological symbolism.','Madhya Pradesh Gond communities sustain visual storytelling art schools.','From wall expression, the form entered canvas and global art spaces.','The art records local mythology, ecology, and social memory.','Training emphasizes line texture, motif rhythm, and layered color.','Shown in museums, biennales, and state art fairs.','Patangarh and Bhopal artists.',1),
    ('classical_art','IN-MH','Warli Painting','Monochrome ritual painting tradition with geometric narrative forms.','Maharashtra tribal belts keep codified ritual drawing and ceremonial wall art.','The school evolved through agrarian ritual contexts and village pedagogy.','It remains an iconic visual language of indigenous India.','Practice focuses on rice-paste linework and compositional symbolism.','Displayed in community festivals and contemporary galleries.','Warli artist cooperatives.',1),
    ('classical_art','IN-MN','Manipuri Sankirtana Performance Art','Classical devotional performance art combining rhythm, voice, and visual movement.','Manipur preserves Vaishnav devotional staging and ceremonial format.','Temple traditions systematized this sacred expressive form.','It anchors ritual calendars and community identity.','Training combines rhythm, textual recitation, and expressive movement.','Presented in temple festivals and cultural academies.','Sankirtana mandali lineages.',1),
    ('classical_art','IN-ML','Wangala Drum-Choreographic Art','Ceremonial drum-led performance art tradition with codified movement motifs.','Meghalaya maintains ceremonial art linked to harvest and clan memory.','Indigenous ritual gatherings shaped this classicalized performance art.','It preserves community history and ceremonial rhythm knowledge.','Practice includes drum grammar, sequence discipline, and ensemble training.','Performed in state cultural showcases and annual festivals.','Garo cultural troupes.',1),
    ('classical_art','IN-MZ','Mizo Bamboo Performance Art','Rhythmic bamboo-structure performance art with precise ensemble timing.','Mizoram keeps bamboo-based performance traditions in formal cultural circuits.','Community ritual spaces institutionalized this art grammar.','The form symbolizes coordination, resilience, and shared identity.','Training emphasizes timing matrices and coordinated movement.','Presented in state and national cultural festivals.','Aizawl heritage ensembles.',1),
    ('classical_art','IN-NL','Naga Woodcarving Heritage Art','Classical carved visual language tied to identity, ritual, and memory.','Nagaland communities preserve symbolic carving forms in ceremonial contexts.','The craft evolved around clan houses and ritual architecture.','Carving motifs archive social memory and status markers.','Pedagogy includes motif vocabulary, carving depth, and finishing.','Shown in tribal museums and state cultural centres.','Naga artisan guilds.',1),
    ('classical_art','IN-OR','Pattachitra Classical Painting','Classical narrative painting with strict iconographic and border grammar.','Odisha keeps temple-linked pattachitra schools and palm-leaf techniques.','Jagannath traditions shaped this canonical visual system.','It remains central to devotional pedagogy and ritual aesthetics.','Training covers natural pigments, line control, and narrative sequencing.','Displayed in heritage villages and museum circuits.','Raghurajpur chitrakar communities.',1),
    ('classical_art','IN-PB','Sikh Fresco-Miniature Heritage Art','Classical fresco and manuscript visual traditions linked to Sikh courts and shrines.','Punjab preserves mural and miniature visual archives in historical sites.','Court ateliers and shrine commissions sustained this artline.','The tradition anchors regional memory and sacred narratives.','Practice includes icon study, restoration methods, and pigment layering.','Featured in heritage conservation and museum exhibits.','Punjabi miniature conservators.',1),
    ('classical_art','IN-RJ','Phad Narrative Scroll Painting','Classical itinerant scroll-painting tradition for epic narration.','Rajasthan keeps Bhopa-Bhopi linked narrative painting canons.','Temple-economy and oral storytelling shaped this visual school.','It fuses portable painting with live performative narration.','Training includes panel sequencing, color coding, and icon script.','Displayed in craft museums and living heritage festivals.','Shahpura phad ateliers.',1),
    ('classical_art','IN-SK','Sikkimese Thangka School','Monastic sacred painting tradition with Himalayan iconographic discipline.','Sikkim monasteries sustain codified thangka visual pedagogy.','Buddhist scholastic transmission formalized painting methods.','It supports contemplative practice and ritual education.','Practice includes canon geometry, mineral pigments, and detail layering.','Shown in monasteries and cultural institutions.','Monastic atelier practitioners.',1),
    ('classical_art','IN-TN','Tanjore Painting','Classical panel painting known for relief, gold foil, and devotional iconography.','Tamil Nadu retains temple-town ateliers preserving Tanjore canons.','Court and temple commissions gave it a refined classical identity.','It remains a major devotional visual culture form.','Training includes board prep, relief work, and icon proportioning.','Displayed in galleries, mutts, and cultural fairs.','Thanjavur lineage artists.',1),
    ('classical_art','IN-TS','Cheriyal Scroll Painting','Classical narrative scroll art with vivid figurative sequencing.','Telangana keeps storyteller-linked scroll painting formats and styles.','Oral performance circuits structured panel sequencing grammar.','The art bridges narrative pedagogy and visual memory.','Practice emphasizes composition blocks, character coding, and color planes.','Showcased in museums and artisan villages.','Cheriyal nakashi families.',1),
    ('classical_art','IN-TR','Tripuri Bamboo-Cane Art','Classical bamboo visual craft tradition with codified motifs and utility forms.','Tripura sustains bamboo-cane artistry in ceremonial and domestic contexts.','Material ecology and craft guilds shaped this heritage.','It preserves indigenous design intelligence and sustainability.','Training includes split preparation, weave geometry, and finishing.','Presented in state craft exhibitions and fairs.','Tripura artisan cooperatives.',1),
    ('classical_art','IN-UP','Banaras Gulabi Meenakari Art','Classical enamel inlay visual tradition with refined pink palette.','Uttar Pradesh preserves Varanasi enamel schools in court-craft continuity.','Jewellery and decorative ateliers built a canonical style grammar.','The art represents precision metal aesthetics and heritage luxury.','Training focuses on engraving, enamel firing, and finishing.','Exhibited in craft museums and premium artisan showcases.','Varanasi meenakar ateliers.',1),
    ('classical_art','IN-UK','Aipan Ritual Floor Art','Classical ritual line-drawing tradition with symbolic geometric layouts.','Uttarakhand maintains ceremonial Aipan forms in domestic and sacred spaces.','Temple and household ritual contexts sustained this visual discipline.','The form encodes auspicious symbolism and seasonal worship practice.','Practice includes motif grammar, red-ochre base, and white linework.','Seen during festivals and state cultural documentation projects.','Kumaoni women artist circles.',1),
    ('classical_art','IN-WB','Kalighat Pat Visual School','Classical painting school known for bold contour and narrative modernity.','West Bengal preserves Kalighat lineage influences in visual pedagogy.','Urban shrine contexts and patua storytelling shaped the style.','The school bridges devotional imagery and social commentary.','Training includes brush economy, wash tone, and narrative framing.','Displayed in museums and folk-art archives.','Kolkata and Bengal patua artists.',1),
    ('classical_art','IN-AN','Nicobari Cane-Shell Art','Island heritage visual craft blending cane and shell material vocabulary.','Andaman and Nicobar communities sustain island craft expression and symbolic motifs.','Maritime ecology shaped material and motif evolution.','The form preserves island memory and community identity.','Practice includes shell treatment, cane weaving, and motif assembly.','Presented in island cultural centres and state fairs.','Nicobari artisan groups.',1),
    ('classical_art','IN-CH','Punjabi Sufi Stage Visual Tradition','Classical stage visual and costume language linked to Sufi musical lineages.','Chandigarh institutions curate North Indian Sufi visual stage traditions.','Modern repertory spaces consolidated the format.','It supports archival and contemporary transmission of devotional stage art.','Training includes set grammar, attire coding, and visual dramaturgy.','Presented in repertory circuits and festivals.','Punjab-Haryana repertory artists.',1),
    ('classical_art','IN-DN','Daman-Diu Coastal Mural Art','Coastal devotional mural and decorative visual art with syncretic motifs.','Dadra and Nagar Haveli and Daman and Diu preserve coastal decorative visual lineages.','Maritime temple and chapel spaces shaped regional visual styles.','It reflects the region''s layered cultural memory.','Practice covers wall prep, pigment layering, and motif grids.','Shown in local heritage events and restoration projects.','Regional mural artisan groups.',1),
    ('classical_art','IN-DL','Delhi Hindustani Stage Art','Classical music-theatre visual staging linked to gharana performance culture.','Delhi''s institutions curate high-culture stage visual grammar.','Courtly and modern auditorium practices refined the format.','The form supports pedagogy, archive, and public dissemination.','Training blends scenography, costume logic, and repertoire context.','Performed in sabhas and national festivals.','Delhi repertory and gharana circles.',1),
    ('classical_art','IN-JK','Kashmiri Papier-Mache Art','Classical painted papier-mache visual craft with courtly floral grammar.','Jammu and Kashmir preserve codified naqashi and sakhtsazi methods.','Court patronage and artisan guilds shaped stylistic canons.','The form is a key identity marker in Kashmiri visual heritage.','Training includes moulding, base layering, and fine brushwork.','Displayed in heritage stores and craft museums.','Srinagar naqash artisans.',1),
    ('classical_art','IN-LA','Ladakhi Monastic Art','Monastic mural and thangka tradition with Himalayan icon precision.','Ladakh monasteries sustain codified visual liturgical arts.','Buddhist scholastic lineages carried painting grammar across generations.','The art supports ritual learning and contemplative practice.','Practice includes icon grids, pigment doctrine, and mural conservation.','Presented in monasteries and cultural archives.','Ladakh monastic painters.',1),
    ('classical_art','IN-LD','Lakshadweep Shell Craft Art','Island shell and coconut-material visual craft with maritime motifs.','Lakshadweep communities preserve island craft vocabularies in ceremonial objects.','Sea-linked livelihoods shaped the craft''s visual expression.','It encodes island ecology and community aesthetics.','Training covers shell finishing, carving, and motif placement.','Shown in island tourism and cultural displays.','Lakshadweep artisan collectives.',1),
    ('classical_art','IN-PY','Puducherry Franco-Tamil Devotional Art','Classical sacred visual traditions shaped by Tamil and French colonial layers.','Puducherry preserves a syncretic sacred-art visual archive.','Temple, church, and academy circuits influenced stylistic evolution.','It reflects the territory''s multilingual and multi-faith visual history.','Training includes icon study, restoration, and devotional visual practice.','Presented in heritage quarters and cultural institutes.','Puducherry heritage artists.',1),
    ('classical_dance','IN-AP','Kuchipudi','Classical dance tradition from Andhra Pradesh with expressive abhinaya and rhythmic precision.','The state preserves Kuchipudi as a major classical repertoire and pedagogy stream.','Temple and court circuits shaped its codified format.','It carries narrative, devotional, and theatrical continuity.','Training focuses on adavus, abhinaya, nattuvangam, and repertoire.','Performed in sabhas, festivals, and university departments.','Vempati lineage and regional gurus.',1),
    ('classical_dance','IN-AR','Ponung Classicalized Tradition','Arunachal performance tradition with ritual movement and chant structures.','Arunachal communities retain codified movement vocabularies in ceremonial practice.','Ritual festivals sustained structured performance lineages.','The form anchors identity and intergenerational continuity.','Pedagogy includes ensemble timing, chant support, and movement grammar.','Presented in state festivals and curated cultural events.','Adi and related community troupes.',1),
    ('classical_dance','IN-AS','Sattriya','Assam''s classical Vaishnav dance tradition with monastic roots.','Sattriya remains a core classical tradition in Assam''s satra institutions.','Neo-Vaishnav monasteries systematized repertoire and pedagogy.','It preserves devotional storytelling and rhythmic sophistication.','Training covers mati akharas, hastas, and dramatic compositions.','Performed in satras and classical stages across India.','Satra gurus and repertory artists.',1),
    ('classical_dance','IN-BR','Bidesia Dance-Theatre Tradition','Narrative dance-theatre tradition with codified folk-classical expression.','Bihar maintains staged Bidesia lineages in cultural circuits.','The form evolved with travelling theatre and regional storytelling.','It captures social memory and performative commentary.','Training integrates dialogue, song, and movement phrasing.','Presented in cultural festivals and regional theatre platforms.','Bhojpuri repertory troupes.',1),
    ('classical_dance','IN-CT','Panthi Dance Tradition','Devotional dance tradition known for stamina, rhythm, and formation aesthetics.','Chhattisgarh sustains Panthi performance in ritual and public settings.','Community devotional gatherings shaped its movement canon.','The form expresses spiritual devotion and collective discipline.','Pedagogy includes percussion mapping and synchronized formations.','Shown in state festivals and national folk-classical showcases.','Satnami cultural ensembles.',1),
    ('classical_dance','IN-GA','Dekhni-Mando Dance Tradition','Goan heritage dance with lyrical movement and theatrical composition.','Goa preserves classicalized coastal repertories through institutions and troupes.','Church, court, and social halls shaped repertoire evolution.','The style reflects syncretic history and maritime aesthetics.','Training combines music phrasing, gesture, and partner dynamics.','Presented in state festivals and heritage programmes.','Goan dance academies.',1),
    ('classical_dance','IN-GJ','Garba-Raas Stage Tradition','Structured circular and narrative dance forms with codified rhythmic cycles.','Gujarat maintains high-discipline stage Garba and Raas repertories.','Temple and seasonal festival contexts built classicalized grammar.','It is central to public ritual and community identity.','Training includes footwork grids, dandiya timing, and formations.','Performed in Navratri circuits and curated stages.','Ahmedabad and Vadodara dance institutions.',1),
    ('classical_dance','IN-HR','Jhumar Stage Tradition','Haryana''s codified group dance style with rhythmic swing and ensemble expression.','State repertories preserve structured Jhumar presentation formats.','Agrarian and festive contexts shaped movement vocabulary.','It represents collective identity and celebratory aesthetics.','Pedagogy covers rhythm cycles, torso sway, and group symmetry.','Shown in state cultural festivals and stage competitions.','Haryana folk dance academies.',1),
    ('classical_dance','IN-HP','Nati Classical Stage Tradition','Codified Nati movement style from Himachal with circular formations.','Himachal institutions preserve region-specific Nati repertoires.','Mountain festive contexts built stable movement and rhythm patterns.','The form encodes seasonal and community life cycles.','Training includes hand patterns, stepping loops, and ensemble timing.','Performed in district festivals and state events.','Kullu and Shimla repertory troupes.',1),
    ('classical_dance','IN-JH','Paika Martial Dance','Martial dance tradition with codified weapon movement and rhythm.','Jharkhand keeps Paika dance forms in ceremonial and stage formats.','Community martial drills evolved into performative grammar.','It preserves resistance memory and physical discipline.','Pedagogy includes stance, prop handling, and drum synchrony.','Presented in state festivals and heritage showcases.','Paika training akharas.',1),
    ('classical_dance','IN-KA','Yakshagana Nritya-Abhinaya','Dance-theatre tradition with codified movement, face expression, and narrative acting.','Karnataka sustains mature Yakshagana schools across coastal belts.','Temple and night-theatre circuits shaped repertoire and pedagogy.','It links dance, music, and dramatic storytelling in one grammar.','Training covers tala discipline, body kinetics, and character abhinaya.','Presented in melas, theatres, and cultural institutions.','Keremane and regional mela lineages.',1),
    ('classical_dance','IN-KL','Mohiniyattam','Classical Kerala dance known for lasya movement and lyrical abhinaya.','Kerala conservatories preserve Mohiniyattam as a core classical system.','Temple and court revival movements stabilized modern pedagogy.','It represents refined feminine expression in classical dance.','Training includes adavus, torso flow, and sahitya-based abhinaya.','Performed in classical circuits and university stages.','Kerala Kalamandalam lineages.',1),
    ('classical_dance','IN-MP','Rai Dance Tradition','Rhythmic performance tradition with codified movement motifs and dramatic flourish.','Madhya Pradesh preserves Rai in stage-ready formats through cultural institutions.','Court and regional performance circuits shaped stylization.','The form reflects local poetics and rhythmic intelligence.','Pedagogy emphasizes rhythm dialogue and expressive movement.','Presented in state and national dance festivals.','Bundelkhand and MP repertory groups.',1),
    ('classical_dance','IN-MH','Lavani Stage Tradition','Maharashtra''s codified dance-theatre style with strong tala and expressive abhinaya.','Lavani remains a major performance tradition in Maharashtra cultural circuits.','Tamasha theatre and court patronage refined stage grammar.','The form archives social themes through music and dance.','Training includes rhythm command, facial expression, and stagecraft.','Performed in theatre circuits and festival stages.','Kolhapur and Pune guru lineages.',1),
    ('classical_dance','IN-MN','Manipuri Ras','Classical dance system of Manipur centered on Vaishnav repertoire.','Manipur preserves Ras tradition through temple and academy pedagogy.','Royal and Vaishnav institutional support codified the repertoire.','It is one of India''s major classical dance canons.','Training includes pung, lasya-tandava balance, and narrative abhinaya.','Performed in Ras mandaps and classical festivals.','Guru Bipin Singh and related lineages.',1),
    ('classical_dance','IN-ML','Nongkrem Dance Tradition','Structured ceremonial dance with codified community movement forms.','Meghalaya continues Nongkrem repertoire through annual festival pedagogy.','Ritual governance and ceremonial contexts shaped dance structures.','The form encodes matrilineal community memory and devotion.','Training focuses on formation integrity, timing, and costume protocol.','Presented in traditional and curated state events.','Khasi cultural ensembles.',1),
    ('classical_dance','IN-MZ','Cheraw Dance','Bamboo dance tradition requiring precise rhythmic coordination and staging discipline.','Mizoram keeps Cheraw as a principal codified performance tradition.','Community ceremonies and festivals preserved and formalized movement grammar.','The form symbolizes collective synchronization and resilience.','Training emphasizes timing matrices between dancers and bamboo operators.','Performed in schools, festivals, and national showcases.','Mizo cultural troupes.',1),
    ('classical_dance','IN-NL','Chang Lo Dance Tradition','Naga ceremonial dance style with codified group movement and narrative motifs.','Nagaland communities preserve staged and ceremonial variants of Chang Lo.','War-memory and festival circuits shaped repertoire evolution.','It transmits identity, ritual memory, and social cohesion.','Pedagogy includes rhythm drills, formation, and costume semantics.','Presented in Hornbill and state festivals.','Nagaland tribal dance ensembles.',1),
    ('classical_dance','IN-OR','Odissi','Odisha''s major classical dance canon with sculptural movement and abhinaya depth.','Odissi remains central to Odisha''s dance pedagogy and festival circuits.','Temple dance and modern revival codified its grammar.','It is a principal Indian classical dance tradition.','Training includes chauka, tribhangi, abhinaya, and pallavi architecture.','Performed in sabhas, temples, and global classical tours.','Kelucharan Mohapatra and Odissi lineages.',1),
    ('classical_dance','IN-PB','Giddha Stage Tradition','Structured Punjabi dance with codified boliyan and ensemble gestures.','Punjab preserves stage and ceremonial Giddha through academies and troupes.','Agrarian festive spaces formalized movement and song formats.','The dance carries women-led collective expression and social memory.','Training combines rhythm phrasing, gesture, and chorus patterns.','Presented in festivals, university teams, and public cultural events.','Punjab dance academies.',1),
    ('classical_dance','IN-RJ','Ghoomar Stage Tradition','Classicalized spin-based dance tradition with codified circular formations.','Rajasthan maintains Ghoomar repertoire in institutional and community settings.','Courtly and festive contexts developed its visual elegance.','The form symbolizes grace, celebration, and regional identity.','Training includes spin control, arm pathways, and group symmetry.','Performed in heritage festivals and state cultural showcases.','Jaipur and Udaipur dance groups.',1),
    ('classical_dance','IN-SK','Singhi Chham','Monastic masked dance tradition with codified ritual choreography.','Sikkim monasteries preserve Chham dance repertoires and ceremonial discipline.','Buddhist ritual cycles shaped movement architecture.','The form communicates sacred narratives and protective symbolism.','Training focuses on mask movement control and ritual timing.','Performed in monastery festivals and state events.','Monastic dance troupes.',1),
    ('classical_dance','IN-TN','Bharatanatyam','Tamil Nadu''s foundational classical dance with codified adavus and abhinaya systems.','Tamil Nadu remains a principal center for Bharatanatyam pedagogy.','Temple heritage and 20th-century revival formalized repertoire structures.','It is among India''s most influential classical dance canons.','Training includes margam progression, nattuvangam, and expressive theory.','Performed in sabhas, festivals, and global tours.','Tanjavur Quartet and modern guru paramparas.',1),
    ('classical_dance','IN-TS','Perini Shivatandavam','Revived warrior dance tradition with codified tandava energy patterns.','Telangana conserves Perini through institutional revival and repertory schools.','Medieval temple and court contexts informed original grammar.','The dance symbolizes martial vigour and Shaiva devotion.','Training emphasizes stamina, rhythmic attack, and torso dynamics.','Presented in festivals and curated classical platforms.','Nataraja Ramakrishna lineage practitioners.',1),
    ('classical_dance','IN-TR','Hojagiri Dance Tradition','Tripura''s codified balancing dance style with rhythmic control.','Tripura maintains Hojagiri as a state-recognized stage tradition.','Community celebrations evolved into refined performance format.','The dance reflects agility, concentration, and ritual celebration.','Training includes balance drills, body control, and folk rhythm work.','Performed in state festivals and national cultural exchanges.','Reang community ensembles.',1),
    ('classical_dance','IN-UP','Kathak','North Indian classical dance canon with strong gharana systems and storytelling.','Uttar Pradesh sustains major Kathak gharanas and performance institutions.','Court, temple, and mehfil traditions shaped the modern repertoire.','It is a principal classical dance form with global reach.','Training covers tatkar, abhinaya, layakari, and repertoire architecture.','Performed in classical sabhas and festival circuits worldwide.','Lucknow and Banaras gharanas.',1),
    ('classical_dance','IN-UK','Chholiya Dance Tradition','Martial dance tradition with codified sword-and-shield choreography.','Uttarakhand keeps Chholiya in ceremonial and stage contexts.','Community rituals and procession customs shaped movement grammar.','It preserves mountain martial memory and festive identity.','Training includes weapon handling, footwork, and formation discipline.','Presented in weddings, fairs, and state cultural events.','Kumaon and Garhwal troupes.',1),
    ('classical_dance','IN-WB','Gaudiya Nritya','Classical Bengali dance revival with devotional and literary repertoire.','West Bengal institutions preserve and expand Gaudiya Nritya pedagogy.','Historic textual references informed modern reconstruction.','The form strengthens Bengal''s classical dance identity.','Training includes codified movement units and Vaishnav narrative expression.','Performed in classical festivals and academy showcases.','Gaudiya Nritya gurus and repertories.',1),
    ('classical_dance','IN-AN','Nicobari Community Dance','Island community dance tradition staged in codified ensemble format.','Andaman and Nicobar preserve island dance idioms through cultural programmes.','Ceremonial and maritime contexts shaped dance patterns.','The form carries island identity and inter-community cohesion.','Training includes rhythm cycles, line formations, and costume protocol.','Presented in island festivals and republic-day showcases.','Nicobari youth cultural groups.',1),
    ('classical_dance','IN-CH','Bhangra Stage Tradition','Structured Punjabi stage dance with codified rhythm-energy modules.','Chandigarh institutions curate formal Bhangra choreography circuits.','Agrarian celebratory forms were adapted into stage canons.','The dance serves identity, celebration, and youth cultural continuity.','Training includes phumman, jhoomar phrasing, and team synchrony.','Performed in university and state-level competitions.','Chandigarh dance academies.',1),
    ('classical_dance','IN-DN','Vira Dance Tradition','Coastal ceremonial dance style with codified rhythmic movement.','Dadra and Nagar Haveli and Daman and Diu preserve local ceremonial dance traditions.','Maritime community rituals influenced movement vocabulary.','The form records regional cultural memory and festivity.','Training includes beat cycles, linework, and costume rhythm.','Presented in local festivals and tourism cultural programmes.','Regional folk-dance groups.',1),
    ('classical_dance','IN-DL','Kathak Rangmanch Circuit','Delhi classical stage ecosystem showcasing Kathak traditions and innovation.','Delhi hosts major classical dance institutions and rangmanch circuits.','National capital institutions expanded classical presentation formats.','The circuit supports pedagogy, archiving, and new productions.','Training blends gharana grammar with stage production practice.','Presented in annual festivals and institutional seasons.','Delhi Kathak repertories.',1),
    ('classical_dance','IN-JK','Rouf Dance Tradition','Kashmiri group dance tradition with codified gentle line movement.','Jammu and Kashmir preserve Rouf in ceremonial and staged contexts.','Seasonal and ritual events shaped movement phrasing.','The dance represents social grace and regional identity.','Training includes coordinated linework and lyrical rhythm response.','Performed in festive gatherings and cultural festivals.','Kashmiri women dance groups.',1),
    ('classical_dance','IN-LA','Cham Dance','Monastic masked ritual dance with codified sacred choreography.','Ladakh monasteries sustain Cham as a major ritual dance canon.','Monastic liturgical calendars preserved choreography and symbolism.','The form transmits doctrinal stories and spiritual practice.','Training includes mask discipline, ritual timing, and dramatic coding.','Performed in monastery festivals and cultural heritage events.','Ladakh monastic troupes.',1),
    ('classical_dance','IN-LD','Lava Dance Tradition','Island rhythmic dance style adapted for stage with codified sequences.','Lakshadweep communities sustain dance repertoires in cultural festivals.','Maritime social gatherings shaped movement and rhythm structures.','The dance reflects island cultural identity and social cohesion.','Training includes beat matching, group entry patterns, and costume rhythm.','Presented in island festivals and state showcases.','Lakshadweep cultural troupes.',1),
    ('classical_dance','IN-PY','Bharatanatyam (Puducherry Bani)','Classical Bharatanatyam pedagogy with Puducherry institutional lineage.','Puducherry preserves strong Bharatanatyam training ecosystems.','Temple and academy routes shaped the territory''s dance identity.','The form connects Tamil classical heritage with local pedagogy.','Training includes margam progression, repertoire, and abhinaya depth.','Performed in sabhas and annual dance festivals.','Puducherry dance academies.',1)
)
INSERT INTO public.cultural_state_items (
  hub_id,
  item_name,
  short_description,
  about_state_tradition,
  history,
  cultural_significance,
  practice_and_pedagogy,
  performance_context,
  notable_exponents,
  discussion_site_id,
  cover_image_url,
  gallery_urls,
  sort_order,
  is_published
)
SELECT
  h.id,
  i.item_name,
  i.short_description,
  i.about_state_tradition,
  i.history,
  i.cultural_significance,
  i.practice_and_pedagogy,
  i.performance_context,
  i.notable_exponents,
  (
    substr(md5(concat(i.category, '|', i.state_code, '|', i.item_name)), 1, 8) || '-' ||
    substr(md5(concat(i.category, '|', i.state_code, '|', i.item_name)), 9, 4) || '-' ||
    substr(md5(concat(i.category, '|', i.state_code, '|', i.item_name)), 13, 4) || '-' ||
    substr(md5(concat(i.category, '|', i.state_code, '|', i.item_name)), 17, 4) || '-' ||
    substr(md5(concat(i.category, '|', i.state_code, '|', i.item_name)), 21, 12)
  )::uuid,
  concat(
    'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/cultural-state/',
    i.category,
    '/',
    lower(replace(i.state_code, 'IN-', '')),
    '/cover.jpg'
  ),
  ARRAY[
    concat(
      'https://xmbygaeixvzlyhbtkbnp.supabase.co/storage/v1/object/public/cultural-state/',
      i.category,
      '/',
      lower(replace(i.state_code, 'IN-', '')),
      '/gallery/1.jpg'
    )
  ]::text[],
  i.sort_order,
  TRUE
FROM item_seed i
JOIN public.cultural_state_hubs h
  ON h.category = i.category
 AND h.state_code = i.state_code
ON CONFLICT (discussion_site_id) DO UPDATE SET
  item_name = EXCLUDED.item_name,
  short_description = EXCLUDED.short_description,
  about_state_tradition = EXCLUDED.about_state_tradition,
  history = EXCLUDED.history,
  cultural_significance = EXCLUDED.cultural_significance,
  practice_and_pedagogy = EXCLUDED.practice_and_pedagogy,
  performance_context = EXCLUDED.performance_context,
  notable_exponents = EXCLUDED.notable_exponents,
  cover_image_url = EXCLUDED.cover_image_url,
  gallery_urls = EXCLUDED.gallery_urls,
  sort_order = EXCLUDED.sort_order,
  is_published = EXCLUDED.is_published;

